homeassistant:
  # Name of the location where Home Assistant is running
  name: Appart
  # Location required to calculate the time the sun rises and sets
  latitude: 48.850773
  longitude: 2.389068
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 35
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here:
  # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Paris

  packages: !include_dir_named packages
  # Customization file
  customize: !include customize.yaml
  # customize_glob:
  auth_providers:
    - type: homeassistant

# Enables the frontend
frontend:
  themes: !include_dir_named themes

# Enables configuration UI
config:

http:
  ip_ban_enabled: true
  login_attempts_threshold: 5
  base_url: !secret base_url

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
    - apple_tv
    - roku
    - google_cast

ios:

# Allows you to issue voice commands from the frontend in enabled browsers
# conversation:

# Enables support for tracking state changes over time
history:
  exclude:
    domains:
      - weblink
      - automation
      - updater
      - weather
    entities:
      - sensor.last_boot
      - sensor.date
      - sun.sun

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
# map:

# Track the sun
sun:
  elevation: 35

# Scenes
scene: !include scene.yaml

# Text to speech
# tts:
#   - platform: google

group: !include groups.yaml
script: !include scripts.yaml

zeroconf:

api:

system_health:

logger:
  default: error
#   logs:
#     pydeconz: debug
#     homeassistant.components.deconz: debug

lovelace:
  mode: yaml

mobile_app:
