homeassistant:
  # Name of the location where Home Assistant is running
  name: Appart
  # Location required to calculate the time the sun rises and sets
  latitude: 48.850773
  longitude: 2.389068
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 35
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here:
  # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Paris

  packages: !include_dir_named packages
  # Customization file
  customize: !include customize.yaml
  # customize_glob:
  auth_providers:
    - type: homeassistant
  external_url: !secret base_url
  internal_url: "http://swarm.home.arpa:8123"

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes

# Enables configuration UI
config:

http:
  ip_ban_enabled: false
  login_attempts_threshold: 5
  # base_url: !secret base_url
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.16.200.0/24

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
# conversation:

# Enables support for tracking state changes over time
history:
  exclude:
    domains:
      - weblink
      - automation
      - updater
      - weather
    entities:
      - sensor.last_boot
      - sensor.date
      - sun.sun

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
# map:

# Track the sun
sun:
  elevation: 35

# Scenes
scene: !include scene.yaml

# Text to speech
# tts:
#   - platform: google

group: !include groups.yaml
script: !include scripts.yaml

zeroconf:

api:

system_health:

#logger:
#  default: error
#  logs:
#    pydeconz: debug
#    homeassistant.components.deconz: debug

# lovelace:
#   mode: yaml
#   resources:
#     - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
#       type: module
#     - url: /hacsfiles/lovelace-mini-graph-card/mini-graph-card-bundle.js
#       type: module
#     - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
#       type: module
#     - url: /hacsfiles/lovelace-valetudo-map-card/valetudo-map-card.js
#       type: module
# #   - url: /local/xiaomi-vacuum-card.js?v=4.4.0
# #     type: module

mobile_app:

stream:
ffmpeg:

automation: !include automations.yaml

my:

template:
  - trigger:
      - platform: webhook
        webhook_id: !secret basement_webhook
    sensor:
      - name: Basement temperature
        state: "{{ trigger.json.uplink_message.decoded_payload.TempC_SHT }}"
        unit_of_measurement: °C
      - name: Basement humidity
        state: "{{ trigger.json.uplink_message.decoded_payload.Hum_SHT }}"
        unit_of_measurement: "%"
        device_class: humidity
      - name: Basement Battery Voltage
        state: "{{ trigger.json.uplink_message.decoded_payload.BatV }}"
        unit_of_measurement: "V"
        device_class: voltage
   # - sensor:
   #    - name: "Basement Battery"
   #      unit_of_measurement: "°%"
   #      device_class: battery
   #      availability: "{{ states('sensor.basement_battery_voltage')|is_number }}"
   #      state: >
   #        {% set batt_volts = states('sensor.basement_battery_voltage')|float(0) %}
   #        {% set batt_pct = 312.5 * batt_volts - 406.25 %} {# calculate percent from the voltage #}
   #        {% set batt_pct_clamped = ([0, batt_pct, 100]|sort)[1] %} {# clamp the output to a 0-100% range #}
   #        {{ batt_pct_clamped }}
