title: Appart
background: center / cover no-repeat url("/local/photos/bg.jpg") fixed

resources:
  - url: /local/custom-lovelace/lovelace-auto-entities/auto-entities.js?v=1
    type: module
  - url: /local/xiaomi-vacuum-card.js?v=3.0.1
    type: module

views:
  - path: default_view
    title: default_view
    badges: []
    icon: 'mdi:home'
    cards:
      - type: vertical-stack
        cards:
          - type: sensor
            graph: line
            name: Dehors
            detail: 2
            entity: sensor.netatmo_dehors_temperature
          - type: glance
            title: Dehors
            show_name: false
            entities:
              - sensor.dark_sky_temperature 
              - weather.dark_sky
              - sensor.netatmo_dehors_humidity
              - sensor.waqi_paris
              - sensor.velib_86245c11064e6c59600ed1a72ca437b7
          - type: picture-glance
            camera_image: camera.vacuum_map
            title: Global
            entities:
              - switch.menage
              - binary_sensor.porte_entree
              - switch.main_water_valve
              - climate.netatmo_my_room
          - type: custom:xiaomi-vacuum-card
            entity: vacuum.rockrobo
            name: false
            image: false
            vendor: valetudo
          - type: entity-filter
            entities:
              - person.capucine
              - person.hana
              - person.emmanuelle
              - person.fabien
              - person.royce
            state_filter:
              - home
            card:
              type: glance
              title: People

      - type: vertical-stack
        cards:
          - type: sensor
            graph: line
            name: Salon
            entity: sensor.netatmo_salon_temperature
            detail: 2
          - type: glance
            title: Salon
            show_name: false
            entities:
              - entity: light.salon
                tap_action:
                  action: toggle
              - entity: light.spots_salon
                tap_action:
                  action: toggle
              - sensor.netatmo_salon_humidity
              - binary_sensor.fenetre_salon
              - entity: fan.ventilateur_bois
                tap_action:
                  action: toggle
              - sensor.netatmo_salon_co2
              - binary_sensor.lumi_sensor_smoke
              - switch.humidifier
          - type: plant-status
            entity: plant.flowall_salon
          - type: picture-entity
            entity: camera.reefab_mainstream

      - type: vertical-stack
        cards:
          - type: sensor
            graph: line
            name: Bureau
            entity: sensor.netatmo_bureau_temperature
            detail: 2
          - type: glance
            title: Bureau
            show_name: false
            entities:
              - entity: light.bureau
                tap_action:
                  action: toggle
              - entity: light.atelier
                tap_action:
                  action: toggle
              - sensor.netatmo_bureau_humidity
              - binary_sensor.fenetre_bureau
              - entity: fan.ventilateur_bureau
                tap_action:
                  action: toggle
              - sensor.netatmo_bureau_co2
              - fan.xiaomi_air_purifier_2s
              - entity: cover.office_blind
                tap_action:
                  action: toggle
              - sensor.bureau_aqi
              - entity: switch.steambox
                icon: 'mdi:steam'
                tap_action:
                  action: toggle
          - type: plant-status
            entity: plant.flowall_bureau
          - type: picture-glance
            title: 3D Printers
            camera_image: camera.3d_printers
            entities:
              - sensor.prusa_current_state
              - binary_sensor.lumi_sensor_smoke_2

      - type: vertical-stack
        cards:
          - type: sensor
            graph: line
            name: chambre
            entity: sensor.netatmo_chambre_temperature
            detail: 2
          - type: glance
            title: Chambre
            show_name: false
            entities:
              - entity: light.chambre
                tap_action:
                  action: toggle
              - entity: light.dressing
                tap_action:
                  action: toggle
              - sensor.netatmo_chambre_humidity
              - entity: cover.bedroom_velux
                tap_action:
                  action: toggle
              - entity: fan.petit_ventilateur
                tap_action:
                  action: toggle
              - sensor.netatmo_chambre_co2
              - fan.xiaomi_air_purifier_2
              - sensor.chambre_aqi
              - binary_sensor.porte_chambre
          - type: glance
            title: Salle de Bain
            show_name: false
            entities:
              - entity: light.salle_de_bain_2
                tap_action:
                  action: toggle
              - sensor.salle_de_bain
              - sensor.salle_de_bain_2
              - binary_sensor.robinet_toilette
          - type: glance
            title: Cuisine
            show_name: false
            entities:
              - entity: light.cuisine
                tap_action:
                  action: toggle
              - sensor.cuisine
              - sensor.cuisine_2
              - binary_sensor.compteur_eau
              - binary_sensor.buanderie
          - type: glance
            title: Mezzanine
            show_name: false
            entities:
              - entity: light.mezzanine
                tap_action:
                  action: toggle
              - sensor.temperature_50
              - sensor.humidity_51
              - entity: cover.velux_mezzanine
                tap_action:
                  action: toggle

  - path: infra_view
    title: infra_view
    badges: []
    icon: 'mdi:server-network'
    cards:
      - type: sensor
        graph: line
        name: Bureau
        entity: sensor.server_rack_temperature
        detail: 2
      - type: entities
        title: Server
        entities:
          - sensor.processor_use
          - sensor.memory_use_percent
          - sensor.nut_ups_battery_runtime
        show_header_toggle: false
      - type: gauge
        entity: sensor.nut_ups_load
      - type: entities
        title: Network
        entities:
          - binary_sensor.routeur
          - binary_sensor.nas
          - binary_sensor.mirror
          - binary_sensor.slice
          - binary_sensor.sliver
          - binary_sensor.slab
          - binary_sensor.ac_ap_lite
          - binary_sensor.imac
        show_header_toggle: false

  - path: media_view
    title: media_view
    badges: []
    icon: 'mdi:presentation-play'
    cards:
      - type: entities
        entities:
          - light.projo
          - light.ecran
          - switch.w1070_blank
          - switch.w1070_3d_fs
          - switch.w1070_3d_tb
          - switch.w1070_3d_sbs
        show_header_toggle: false
        title: Light
      - type: media-control
        entity: media_player.ecran_salon

  - path: settings_view
    title: settings_view
    badges: []
    cards:
      - type: entities
        title: Script
        show_header_toggle: false
        entities:
          - script.restart_ha
          - script.check_config
      - type: custom:auto-entities
        title: all automations
        card:
          type: entities
          show_header_toggle: false
        filter:
          include:
            - domain: automation
    icon: 'mdi:settings'

  - path: battery_view
    title: Batteries
    icon: 'mdi:battery-alert'
    badges: []
    cards:
      - type: custom:auto-entities
        card:
          type: entities
        filter:
          include:
            - group: group.battery_status
      - type: custom:auto-entities
        card:
          type: entities
        filter:
          include:
            - group: group.battery_alert

  - path: test
    title: Test
    badges: []
    cards:
      - type: entities
        entities:
          - sensor.airtower_temperature
          - sensor.airtower_humidity
          - sensor.airtower_pressure
          - sensor.airtower_ammonia
          - sensor.airtower_oxidising_gases
          - sensor.airtower_reducing_gases
          - sensor.airtower_light
          - sensor.airtower_pm_1
          - sensor.airtower_pm_2_5
          - sensor.airtower_pm_10

