title: Appart
background: center / cover no-repeat url("/local/photos/bg.jpg") fixed

resources:
  - url: /local/toggle-lock-entity-row.js
    type: js
  - url: /local/custom-lovelace/compact-custom-header/compact-custom-header.js?v=0.0.2
    type: module

views:
  - path: default_view
    title: default_view
    badges: []
    icon: 'mdi:home'
    cards:
      - type: custom:compact-custom-header
      - type: vertical-stack
        cards:
          - type: glance
            show_name: false
            entities:
              - vacuum.xiaomi_vacuum_cleaner
              - switch.flux
              - binary_sensor.porte_entree
            title: Global
          - type: thermostat
            entity: climate.netatmo_my_room
          - type: entities
            entities:
              - entity: switch.main_water_valve
                type: custom:toggle-lock-entity-row
      - type: vertical-stack
        cards:
          - type: glance
            title: Salon
            show_name: false
            entities:
              - entity: light.spots_salon
                tap_action:
                  action: toggle
              - sensor.netatmo_salon_temperature
              - sensor.netatmo_salon_humidity
              - binary_sensor.fenetre_salon
              - entity: fan.ventilateur_bois
                tap_action:
                  action: toggle
              - binary_sensor.lumi_sensor_smoke
              - sensor.foobot_salon_co2
              - sensor.foobot_salon_pm25
              - sensor.foobot_salon_voc
              - sensor.foobot_salon_index
          - type: horizontal-stack
            cards:
              - type: light
                entity: light.salon
              - type: sensor
                graph: line
                entity: sensor.netatmo_salon_temperature
      - type: vertical-stack
        cards:
          - type: glance
            title: Bureau
            show_name: false
            entities:
              - entity: light.vitrine
                tap_action:
                  action: toggle
              - binary_sensor.openclose_11
              - sensor.netatmo_bureau_humidity
              - entity: fan.ventilateur_bureau
                tap_action:
                  action: toggle
              - fan.xiaomi_air_purifier_2
              - sensor.netatmo_bureau_noise
              - sensor.netatmo_bureau_co2
              - sensor.bureau_aqi
              - switch.soldering_iron
              - binary_sensor.fire_37
              - entity: switch.steambox
                icon: 'mdi:steam'
                tap_action:
                  action: toggle
          - type: horizontal-stack
            cards:
              - type: light
                entity: light.bureau
              - type: sensor
                graph: line
                entity: sensor.netatmo_bureau_temperature

      - type: glance
        title: Chambre
        show_name: false
        entities:
          - sensor.netatmo_chambre_temperature
          - sensor.netatmo_chambre_humidity
          - entity: fan.petit_ventilateur
            tap_action:
              action: toggle
          - sensor.netatmo_chambre_co2
          - entity: cover.bedroom_velux
            tap_action:
              action: toggle
      - type: glance
        title: Salle de Bain
        show_name: false
        entities:
          - entity: light.salle_de_bain_2
            tap_action:
              action: toggle
          - sensor.salle_de_bain_2
          - sensor.salle_de_bain_3
          - binary_sensor.water_12
      - type: glance
        title: Cuisine
        show_name: false
        entities:
          - entity: light.cuisine_2
            tap_action:
              action: toggle
          - sensor.cuisine_2
          - sensor.cuisine_3
          - sensor.fridge_power
          - binary_sensor.compteur_eau
          - binary_sensor.buanderie
      - type: glance
        title: Mezzanine
        show_name: false
        entities:
          - entity: light.mezzanine_2
            tap_action:
              action: toggle
          - entity: cover.velux_mezzanine
            tap_action:
              action: toggle
      - type: vertical-stack
        cards:
          - type: glance
            title: Dehors
            show_name: false
            entities:
              - sensor.netatmo_dehors_temperature
              - sensor.netatmo_dehors_humidity
              - sensor.waqi_paris_centre_paris
              - sensor.velib_86245c11064e6c59600ed1a72ca437b7
          - type: weather-forecast
            entity: weather.dark_sky
      - type: vertical-stack
        cards:
          - type: plant-status
            entity: plant.flowall_bureau
          - type: plant-status
            entity: plant.flowall_salon
      - type: vertical-stack
        cards:
          - type: picture-glance
            title: 3D Printers
            camera_image: camera.3d_printers
            entities:
              - sensor.r2r_current_state
              - sensor.r2r_job_percentage
              - sensor.itopie_current_state
              - sensor.itopie_job_percentage
          - type: entities
            entities:
              - entity: switch.3d_printers
                name: 3D printers
                type: custom:toggle-lock-entity-row
      - type: entity-filter
        entities:
          - device_tracker.phophone
          - device_tracker.iphonedmanuelle
          - device_tracker.huawei_p9_lite_premium
          - device_tracker.oneplus_5t
        state_filter:
          - home
        card:
          type: glance
          title: People

  - path: infra_view
    title: infra_view
    badges: []
    icon: 'mdi:server-network'
    cards:
      - type: custom:compact-custom-header
      - type: entities
        title: Server
        entities:
          - sensor.processor_use
          - sensor.memory_use_percent
          - sensor.plex
          - sensor.pi_hole_ads_blocked_today
          - sensor.nut_ups_battery_runtime
          - sensor.nut_ups_load
        show_header_toggle: false
      - type: entities
        title: Network
        entities:
          - binary_sensor.routeur
          - binary_sensor.nas
          - binary_sensor.pi_hole_2
          - binary_sensor.sync
          - binary_sensor.ac_ap_lite
        show_header_toggle: false

  - path: media_view
    title: media_view
    badges: []
    cards:
      - type: custom:compact-custom-header
      - type: entities
        entities:
          - light.salon
          - script.blank_projector
          - script.restore_projector
        show_header_toggle: false
        title: Light
      - type: media-control
        entity: media_player.ecran_salon
    icon: 'mdi:presentation-play'

  - path: settings_view
    title: settings_view
    badges: []
    cards:
      - type: custom:compact-custom-header
      - type: entities
        entities:
          - automation.close_covers_at_night
          - automation.open_bedroom_cover_during_the_day
          - automation.open_mezzanine_cover_during_the_day
          - >-
            automation.prompt_to_open_windows_if_exterior_temperature_is_below_living_room_temperature
          - >-
            automation.prompt_to_open_windows_if_exterior_temperature_is_below_office_temperature
          - automation.quieten_vacuum_if_back_home_alone
          - automation.shut_water_valve_in_case_of_leaks
          - automation.soldering_iron_still_on
          - automation.start_clearning_before_it_s_too_late
          - automation.start_clearning_if_home_is_empty
          - automation.stop_vacuum_if_back_home_with_guests
          - automation.switch_flux_mode_on_at_start_up
          - automation.switch_all_lights_off_with_button_press
          - automation.switch_lights_off_if_no_one_is_home
          - automation.switch_lights_on_if_people_are_coming_home
          - automation.switch_lights_on_if_people_are_home_at_sunset
          - automation.toggle_bed_fan
          - automation.toggle_bedroom_cover
          - automation.turn_off_humidifier_if_it_s_too_humid
          - automation.turn_off_office_purifier_if_aqi_is_fine
          - automation.turn_on_humidifier_if_it_s_too_dry
          - automation.turn_on_office_purifier_if_aqi_is_too_low
          - >-
            automation.turn_stuff_back_on_when_the_windows_are_closed_or_there_is_people
          - automation.turn_stuff_off_when_a_window_is_opened_or_no_home_is_one
          - automation.battery_notification
          - automation.battery_notification_clear
          - automation.battery_sensor_from_attributes
          - automation.clear_mqtt_topic
          - automation.front_door_has_been_opened
          - automation.mute_volume_with_cube
          - automation.switch_entrance_light_on_door_opening
          - automation.toggle_fans_with_cube
          - automation.turn_down_volume_with_cube
          - automation.turn_office_fan_off
          - automation.turn_office_fan_on
          - automation.turn_up_volume_with_cube
          - automation.update_battery_status_group_members
        title: all automations
        show_header_toggle: false
      - type: entities
        entities:
          - input_number.battery_alert_threshold_min
          - input_number.battery_alert_threshold_max
          - input_text.clear_mqtt_topic
          - automation.battery_notification
          - automation.battery_notification_clear
          - automation.battery_sensor_from_attributes
          - automation.update_battery_status_group_members
          - automation.clear_mqtt_topic
        title: Battery Alert
        show_header_toggle: false
      - type: entities
        entities:
          - script.restart_ha
          - script.check_config
        title: Script
    icon: 'mdi:settings'
  - path: battery_view
    title: Batteries
    badges: []
    cards:
      - type: custom:compact-custom-header
      - type: entities
        entities:
          - sensor.arrivee_eau_battery
          - sensor.bouton_lit_battery
          - sensor.buanderie_battery
          - sensor.bureau_battery_level
          - sensor.compteur_eau_battery
          - sensor.cube_158d000104d0ed_battery
          - sensor.fabien_battery
          - sensor.fenetre_bureau_battery
          - sensor.fenetre_salon_battery
          - sensor.fenetre_salon_battery_2
          - sensor.flowall_bureau_battery_2
          - sensor.flowall_bureau_xiaomi_battery
          - sensor.flowall_salon_battery
          - sensor.flowall_salon_xiaomi_battery
          - sensor.fumee_salon_battery
          - sensor.fumee_salon_battery_2
          - sensor.humidite_battery
          - sensor.humidite_battery_2
          - sensor.humidite_cuisine_battery
          - sensor.humidite_sdb_battery
          - sensor.lightlevel_28_battery
          - sensor.lightlevel_59_battery
          - sensor.lit_battery_level
          - sensor.motion_sensor_battery
          - sensor.mouvement_salle_de_bain_battery
          - sensor.netatmo_chambre_battery
          - sensor.netatmo_chambre_battery_percent
          - sensor.netatmo_dehors_battery
          - sensor.netatmo_dehors_battery_percent
          - sensor.netatmo_salon_battery
          - sensor.netatmo_salon_battery_percent
          - sensor.openclose_11_battery
          - sensor.porte_entree_battery
          - sensor.porte_entree_battery_2
          - sensor.presence_26_battery
          - sensor.presence_58_battery
          - sensor.pression_cuisine_battery
          - sensor.pression_cuisine_battery_2
          - sensor.pression_salle_de_bain_battery
          - sensor.pression_sdb_battery
          - sensor.robinet_lave_lingevaisselle_battery
          - sensor.robinet_toilette_battery
          - sensor.robinet_toilette_battery_2
          - sensor.roborock_vacuum_battery
          - sensor.salon_battery_level
          - sensor.salon_chambre_battery_level
          - sensor.salon_mezza_battery_level
          - sensor.spare_battery
          - sensor.switch_19_battery_level
          - sensor.switch_57_battery_level
          - sensor.temperature_27_battery
          - sensor.temperature_battery
          - sensor.temperature_battery_2
          - sensor.temperature_cuisine_battery
          - sensor.temperature_sdb_battery
        title: Battery Status
        show_header_toggle: false
    icon: 'mdi:battery-alert'
