title: Appart

views:
  - path: default_view
    title: default_view
    badges: []
    icon: 'mdi:home'
    cards:
      - type: vertical-stack
        cards:
          - type: sensor
            graph: line
            name: Dehors
            detail: 2
            entity: sensor.netatmo_mezon_bureau_dehors_temperature
          - type: glance
            title: Dehors
            show_name: false
            entities:
              - sensor.dark_sky_temperature
              - weather.dark_sky
              - sensor.netatmo_mezon_bureau_dehors_humidity
              - sensor.lightlevel_70
              - sensor.waqi_paris
          - type: picture-glance
            camera_image: camera.vacuum_map
            title: Global
            entities:
              - switch.adaptive_lighting_global
              - switch.menage
              - switch.mop
              - climate.netatmo_my_room
          - type: custom:xiaomi-vacuum-card
            entity: vacuum.rockrobo
            name: false
            image: false
            vendor: valetudo
          - type: entity-filter
            entities:
              - person.capucine
              - person.hana
              - person.emmanuelle
              - person.fabien
              - person.royce
            state_filter:
              - home
            card:
              type: glance
              title: People

      - type: vertical-stack
        cards:
          - type: sensor
            graph: line
            name: Salon
            entity: sensor.netatmo_mezon_bureau_salon_temperature
            detail: 2
          - type: glance
            title: Salon
            show_name: false
            entities:
              - entity: light.salon
                tap_action:
                  action: toggle
              - entity: light.spots_salon
                tap_action:
                  action: toggle
              - sensor.netatmo_mezon_bureau_salon_humidity
              - binary_sensor.fenetre_salon
              - entity: fan.ventilateur_salon
                tap_action:
                  action: toggle
              - sensor.netatmo_mezon_bureau_salon_co2
              - fan.xiaomi_evaporative_humidifier_cb1
              - entity: cover.living_room_blind
                tap_action:
                  action: toggle
              - binary_sensor.lumi_sensor_smoke
              - entity: sensor.flowallsalon_moisture
                icon: 'mdi:sprout'
          - type: picture-glance
            title: Salon
            camera_image: camera.tapo_camera_hd
            # camera_view: live
            hold_action:
              action: more-info
            entities:
              - entity: camera.tapo_camera_hd
                icon: 'mdi:arrow-left-drop-circle-outline'
                tap_action:
                  action: call-service
                  service: tapo_control.ptz
                  service_data:
                    entity_id: camera.tapo_camera_hd
                    pan: LEFT
              - entity: camera.tapo_camera_hd
                icon: 'mdi:arrow-up-drop-circle-outline'
                tap_action:
                  action: call-service
                  service: tapo_control.ptz
                  service_data:
                    entity_id: camera.tapo_camera_hd
                    tilt: UP
              - entity: camera.tapo_camera_hd
                icon: 'mdi:arrow-down-drop-circle-outline'
                tap_action:
                  action: call-service
                  service: tapo_control.ptz
                  service_data:
                    entity_id: camera.tapo_camera_hd
                    tilt: DOWN
              - entity: camera.tapo_camera_hd
                icon: 'mdi:arrow-right-drop-circle-outline'
                tap_action:
                  action: call-service
                  service: tapo_control.ptz
                  service_data:
                    entity_id: camera.tapo_camera_hd
                    pan: RIGHT
              - entity: switch.camera_privacy_mode
                icon: 'mdi:eye-outline'
                tap_action:
                  action: toggle
                  service: tapo_control.set_privacy_mode
                  service_data:
                    entity_id: camera.tapo_camera_hd
                    privacy_mode: 'off'
              - entity: camera.tapo_camera_hd
                icon: 'mdi:power'
                tap_action:
                  action: call-service
                  confirmation: true
                  service: tapo_control.reboot
                  service_data:
                    entity_id: camera.tapo_camera_hd

      - type: vertical-stack
        cards:
          - type: sensor
            graph: line
            name: Bureau
            entity: sensor.netatmo_mezon_bureau_temperature
            detail: 2
          - type: glance
            title: Bureau
            show_name: false
            entities:
              - entity: light.bureau
                tap_action:
                  action: toggle
              - entity: light.atelier
                tap_action:
                  action: toggle
              - sensor.netatmo_mezon_bureau_humidity
              - binary_sensor.fenetre_bureau
              - entity: fan.ventilateur_bureau
                tap_action:
                  action: toggle
              - sensor.netatmo_mezon_bureau_co2
              - fan.xiaomi_air_purifier_2s
              - entity: cover.office_blind
                tap_action:
                  action: toggle
              - sensor.bureau_aqi
              - entity: sensor.flowallbureau_moisture
                icon: 'mdi:sprout'
          - type: picture-glance
            title: 3D Printers
            camera_image: camera.3d_printers
            entities:
              - entity: switch.prusa
                tap_action:
                  action: toggle
                  confirmation: true
              - entity: light.atelier
                tap_action:
                  action: toggle
                icon: 'mdi:lightbulb'
              - entity: sensor.prusa_current_state
                icon: 'mdi:printer-3d-nozzle'
              - binary_sensor.lumi_sensor_smoke_2

      - type: vertical-stack
        cards:
          - type: sensor
            graph: line
            name: chambre
            entity: sensor.netatmo_mezon_bureau_chambre_temperature
            detail: 2
          - type: glance
            title: Chambre
            show_name: false
            entities:
              - entity: light.chambre
                tap_action:
                  action: toggle
              - entity: light.dressing
                tap_action:
                  action: toggle
              - sensor.netatmo_mezon_bureau_chambre_humidity
              - binary_sensor.porte_chambre
              - entity: fan.petit_ventilateur
                tap_action:
                  action: toggle
              - sensor.netatmo_mezon_bureau_chambre_co2
              - fan.xiaomi_air_purifier_2
              - entity: cover.bedroom_blind
                tap_action:
                  action: toggle
              - sensor.chambre_aqi

          - type: glance
            title: Salle de Bain
            show_name: false
            entities:
              - entity: light.salle_de_bain_2
                tap_action:
                  action: toggle
              - sensor.temperature_48
              - sensor.humidity_68
              - binary_sensor.robinet_toilette

          - type: glance
            title: Cuisine
            show_name: false
            entities:
              - entity: light.cuisine
                tap_action:
                  action: toggle
              - sensor.cuisine
              - sensor.cuisine_2
              - binary_sensor.compteur_eau
              - binary_sensor.buanderie
              - binary_sensor.carbonmonoxide_67
              - binary_sensor.porte_entree
              - entity: switch.water_valve
                tap_action:
                  action: toggle
                  confirmation: true

          - type: glance
            title: Mezzanine
            show_name: false
            entities:
              - entity: light.mezzanine
                tap_action:
                  action: toggle
              - sensor.temperature_50
              - sensor.humidity_51
              - entity: cover.velux_mezzanine
                tap_action:
                  action: toggle

  - path: infra_view
    title: infra_view
    badges: []
    icon: 'mdi:server-network'
    cards:
      - type: sensor
        graph: line
        name: Rack temperature
        entity: sensor.salle_de_bain
        detail: 2
      - type: entities
        title: Server
        entities:
          - sensor.processor_use
          - sensor.memory_use_percent
          - sensor.nut_ups_battery_runtime
        show_header_toggle: false
      - type: gauge
        entity: sensor.nut_ups_load
      - type: entities
        title: Network
        entities:
          - binary_sensor.routeur
          - binary_sensor.deconz
          - binary_sensor.pi
          - binary_sensor.nas
          - binary_sensor.mirror
          - binary_sensor.slice
          - binary_sensor.sliver
          - binary_sensor.slab
          - binary_sensor.ac_ap_lite
          - binary_sensor.imac
        show_header_toggle: false

  - path: media_view
    title: media_view
    badges: []
    icon: 'mdi:presentation-play'
    cards:
      - type: media-control
        entity: media_player.ecran_salon
      - type: entities
        entities:
          - switch.steambox
          - light.salon
          - light.wled
          - light.first_led_hardware_instance
          - switch.first_led_hardware_instance_component_platform_capture
          - switch.w1070_blank
          - switch.w1070_3d_fs
          - switch.w1070_3d_tb
          - switch.w1070_3d_sbs
        show_header_toggle: false

  - path: music_view
    title: music_view
    badges: []
    icon: 'mdi:music'
    cards:
      - type: media-control
        entity: media_player.yamaha_receiver
      - type: entities
        entities:
          - switch.light_15
          - switch.on_off_plug_in_unit_21
        show_header_toggle: false

  - path: night_view
    title: night_view
    badges: []
    icon: 'mdi:weather-night'
    cards:
      - type: media-control
        entity: media_player.forked_daapd_server
      - type: entities
        show_header_toggle: false
        entities:
          - input_boolean.night_time
          - input_select.night_time_playlist
          - switch.ambient_audio

  - path: settings_view
    title: settings_view
    badges: []
    cards:
      - type: entities
        title: Script
        show_header_toggle: false
        entities:
          - script.restart_ha
          - script.check_config
      - type: custom:auto-entities
        title: all automations
        card:
          type: entities
          show_header_toggle: false
        filter:
          include:
            - domain: automation
    icon: 'mdi:cog'

  - path: battery_view
    title: Batteries
    icon: 'mdi:battery-alert'
    badges: []
    cards:
      - type: custom:auto-entities
        card:
          type: entities
        filter:
          include:
            - group: group.battery_status
      - type: custom:auto-entities
        card:
          type: entities
        filter:
          include:
            - group: group.battery_alert

  - path: test
    title: Test
    badges: []
    cards:
      - type: entities
        entities:
          - sensor.airtower_temperature
          - sensor.airtower_humidity
          - sensor.airtower_pressure
          - sensor.airtower_ammonia
          - sensor.airtower_oxidising_gases
          - sensor.airtower_reducing_gases
          - sensor.airtower_light
          - sensor.airtower_pm_1
          - sensor.airtower_pm_2_5
          - sensor.airtower_pm_10
