title: Appart
background: center / cover no-repeat url("/local/photos/bg.jpg") fixed

resources:
  - url: /local/toggle-lock-entity-row.js
    type: js
  - url: /local/custom-lovelace/compact-custom-header/compact-custom-header.js?v=0.0.2
    type: module
  - url: /local/custom-lovelace/group-card/group-card.js
    type: js

views:
  - path: default_view
    title: default_view
    badges: []
    icon: 'mdi:home'
    cards:
      - type: vertical-stack
        cards:
          - type: thermostat
            entity: climate.netatmo_my_room
          - type: sensor
            graph: line
            name: Dehors
            entity: sensor.netatmo_dehors_temperature
          - type: glance
            title: Global
            entities:
              - vacuum.xiaomi_vacuum_cleaner
              - switch.circadian_lighting_circadian_lighting
              - binary_sensor.porte_entree
              - entity: switch.main_water_valve
                type: custom:toggle-lock-entity-row
          - type: glance
            title: Dehors
            entities:
              - sensor.netatmo_dehors_humidity
              - sensor.waqi_paris_centre_paris
              - sensor.velib_86245c11064e6c59600ed1a72ca437b7

          - type: weather-forecast
            entity: weather.dark_sky
          - type: entity-filter
            entities:
              - device_tracker.phophone
              - device_tracker.iphonedmanuelle
              - device_tracker.huawei_p9_lite_premium
              - device_tracker.oneplus_5t
            state_filter:
              - home
            card:
              type: glance
              title: People

      - type: vertical-stack
        cards:
          - type: light
            entity: light.salon
          - type: sensor
            graph: line
            name: Salon
            entity: sensor.netatmo_salon_temperature
          - type: glance
            title: Salon
            show_name: false
            entities:
              - entity: light.spots_salon
                tap_action:
                  action: toggle
              - sensor.netatmo_salon_humidity
              - binary_sensor.fenetre_salon
              - entity: fan.ventilateur_bois
                tap_action:
                  action: toggle
              - sensor.foobot_salon_co2
              - binary_sensor.lumi_sensor_smoke
              - sensor.foobot_salon_pm25
              - sensor.foobot_salon_voc
              - sensor.foobot_salon_index
          - type: plant-status
            entity: plant.flowall_salon

      - type: vertical-stack
        cards:
          - type: light
            entity: light.bureau
          - type: sensor
            graph: line
            name: Bureau
            entity: sensor.netatmo_bureau_temperature
          - type: glance
            title: Bureau
            show_name: false
            entities:
              - entity: light.vitrine
                tap_action:
                  action: toggle
              - sensor.netatmo_bureau_humidity
              - binary_sensor.openclose_11
              - entity: fan.ventilateur_bureau
                tap_action:
                  action: toggle
              - sensor.netatmo_bureau_co2
              - fan.xiaomi_air_purifier_2
              - sensor.netatmo_bureau_noise
              - sensor.bureau_aqi
              - switch.soldering_iron
              - entity: switch.steambox
                icon: 'mdi:steam'
                tap_action:
                  action: toggle
          - type: plant-status
            entity: plant.flowall_bureau
          - type: picture-glance
            title: 3D Printers
            camera_image: camera.3d_printers
            entities:
              - sensor.r2r_current_state
              - sensor.itopie_current_state
              - binary_sensor.fire_37
          - type: entities
            entities:
              - entity: switch.3d_printers
                name: 3D printers
                type: custom:toggle-lock-entity-row

      - type: vertical-stack
        cards:
          - type: light
            entity: light.chambre
          - type: sensor
            graph: line
            name: chambre
            entity: sensor.netatmo_chambre_temperature
          - type: glance
            title: Chambre
            show_name: false
            entities:
              - entity: light.dressing
                tap_action:
                  action: toggle
              - sensor.netatmo_chambre_humidity
              - entity: cover.bedroom_velux
                tap_action:
                  action: toggle
              - entity: fan.petit_ventilateur
                tap_action:
                  action: toggle
              - sensor.netatmo_chambre_co2

      - type: glance
        title: Salle de Bain
        show_name: false
        entities:
          - entity: light.salle_de_bain_2
            tap_action:
              action: toggle
          - sensor.salle_de_bain_3
          - sensor.salle_de_bain_2
          - binary_sensor.water_12

      - type: glance
        title: Cuisine
        show_name: false
        entities:
          - entity: light.cuisine_2
            tap_action:
              action: toggle
          - sensor.cuisine_3
          - sensor.cuisine_2
          - sensor.fridge_power
          - binary_sensor.compteur_eau
          - binary_sensor.buanderie

      - type: glance
        title: Mezzanine
        show_name: false
        entities:
          - entity: light.mezzanine_2
            tap_action:
              action: toggle
          - entity: cover.velux_mezzanine
            tap_action:
              action: toggle


  - path: infra_view
    title: infra_view
    badges: []
    icon: 'mdi:server-network'
    cards:
      - type: entities
        title: Server
        entities:
          - sensor.processor_use
          - sensor.memory_use_percent
          - sensor.plex
          - sensor.pi_hole_ads_blocked_today
          - sensor.nut_ups_battery_runtime
          - sensor.nut_ups_load
        show_header_toggle: false
      - type: entities
        title: Network
        entities:
          - binary_sensor.routeur
          - binary_sensor.nas
          - binary_sensor.pi_hole_2
          - binary_sensor.sync
          - binary_sensor.ac_ap_lite
          - binary_sensor.imac
        show_header_toggle: false

  - path: media_view
    title: media_view
    badges: []
    cards:
      - type: entities
        entities:
          - light.salon
          - script.blank_projector
          - script.restore_projector
        show_header_toggle: false
        title: Light
      - type: media-control
        entity: media_player.ecran_salon
    icon: 'mdi:presentation-play'

  - path: settings_view
    title: settings_view
    badges: []
    cards:
      - type: entities
        title: Script
        show_header_toggle: false
        entities:
          - script.restart_ha
          - script.check_config
      - type: custom:group-card
        title: all automations
        card:
          type: entities
          show_header_toggle: false
        group: group.all_automations
    icon: 'mdi:settings'

  - path: test
    title: Test
    badges: []
    cards:
      - type: entities
        entities:
          - sensor.airtower_temperature
          - sensor.airtower_humidity
          - sensor.airtower_pressure
          - sensor.airtower_ammonia
          - sensor.airtower_oxidising_gases
          - sensor.airtower_reducing_gases
          - sensor.airtower_light
          - sensor.airtower_pm_1
          - sensor.airtower_pm_2_5
          - sensor.airtower_pm_10

  - path: battery_view
    title: Batteries
    icon: 'mdi:battery-alert'
    badges: []
    cards:
      - type: custom:group-card
        card:
          type: entities
        group: group.battery_status
      - type: custom:group-card
        card:
          type: entities
        group: group.battery_alert
