# Webcam monitoring
camera:
  - platform: mjpeg
    name: 3d printers
    mjpeg_url: http://192.168.1.49/webcam/?action=stream
    still_image_url: http://192.168.1.49/webcam/?action=snapshot

automation:
  - alias: 🖨 Cut power to 3D printers in case of smoke
    trigger:
      - platform: state
        from: 'off'
        to: 'on'
        entity_id: binary_sensor.smoke_2_smoke
    action:
      service: switch.turn_off
      entity_id: switch.prusa
  - alias: 🖨 Switch power off when idling for too long
    trigger:
      - platform: state
        to: 'off'
        for: '01:00:00'
        entity_id: binary_sensor.octoprint_printing
    action:
      service: switch.turn_off
      entity_id: switch.prusa
  - alias: 🖨 Send notification when printing is done
    trigger:
      - platform: state
        entity_id: binary_sensor.octoprint_printing
        from: 'on'
        to: 'off'
    condition:
      # to filter out prints cancelled before the end
      - condition: numeric_state
        entity_id: sensor.octoprint_job_percentage
        above: 95
    action:
      - service: light.turn_on
        entity_id: light.atelier
      - delay:
          seconds: 5
      - service: notify.main_devices
        data:
          message: 'Print finished.'
          data:
            attachment:
              content-type: jpeg
            push:
              category: camera
            entity_id: camera.3d_printers
      - service: light.turn_off
        entity_id: light.atelier

switch:
  - platform: command_line
    switches:
      # I use https://github.com/Z-Bolt/OctoScreen to control octoprint via a touch screen directly connected to the raspberry pi
      # GPIO pins. It does have an issue: if the printer is off and thus octoprint is not connected to it, it'll keep trying to connect
      # and it eventually makes octoprint crash (known bug). So this switch is used to disable it alongside the printer power supply.
      # Cool side effect: it'll make octoprint connect to the printer automatically when started.
      octoprint_screen:
        command_on: ssh -i /config/id_rsa_octopi -o 'StrictHostKeyChecking no' pi@192.168.1.49 'sudo service octoscreen start'
        command_off: ssh -i /config/id_rsa_octopi -o 'StrictHostKeyChecking no' pi@192.168.1.49 'sudo service octoscreen stop'
        command_timeout: 60  # it can be pretty slow sometimes, not to actually start or stop but for the command to finish
  - platform: template
    switches:
      prusa:
        turn_on:
          - service: switch.turn_on
            entity_id: switch.ikea_plug_1
          - service: switch.turn_on
            entity_id: switch.octoprint_screen
        turn_off:
          - service: switch.turn_off
            entity_id: switch.ikea_plug_1
          - service: switch.turn_off
            entity_id: switch.octoprint_screen

homeassistant:
  customize:
    switch.prusa:
      friendly_name: Prusa Mk3s
      icon: mdi:printer-3d
