# 2 3D printers, each with their https://octoprint.org server
octoprint:
  - host: 192.168.1.49
    name: prusa
    api_key: !secret octoprint_r2r_api
    bed: true
    number_of_tools: 1
    sensors:
      monitored_conditions:
        - Current State
        - Job Percentage
    binary_sensors:
      monitored_conditions:
        - Printing

# Webcam monitoring, actually running in a mjpeg streamer docker container
camera:
  - platform: mjpeg
    name: 3d printers
    mjpeg_url: http://192.168.1.49/webcam/?action=stream
    still_image_url: http://192.168.1.49/webcam/?action=snapshot

automation:
  - alias: Cut power to 3D printers in case of smoke
    trigger:
      - platform: state
        from: 'off'
        to: 'on'
        entity_id: binary_sensor.lumi_sensor_smoke_2
    action:
      service: switch.turn_off
      entity_id: switch.3d_printers
