# 3D printer with a https://octoprint.org server
octoprint:
  - host: 192.168.1.49
    name: prusa
    api_key: !secret octoprint_r2r_api
    bed: true
    number_of_tools: 1
    sensors:
      monitored_conditions:
        - Current State
        - Job Percentage
    binary_sensors:
      monitored_conditions:
        - Printing

# Webcam monitoring
camera:
  - platform: mjpeg
    name: 3d printers
    mjpeg_url: http://192.168.1.49/webcam/?action=stream
    still_image_url: http://192.168.1.49/webcam/?action=snapshot

automation:
  - alias: Cut power to 3D printers in case of smoke
    trigger:
      - platform: state
        from: 'off'
        to: 'on'
        entity_id: binary_sensor.lumi_sensor_smoke_2
    action:
      service: switch.turn_off
      entity_id: switch.on_off_plug_in_unit_20
  - alias: Switch power off when idling for too long
    trigger:
      - platform: state
        to: 'off'
        for: '01:00:00'
        entity_id: binary_sensor.prusa_printing
    action:
      service: switch.turn_off
      entity_id: switch.on_off_plug_in_unit_20
  - alias: Send notification when printing is done
    trigger:
      - platform: state
        entity_id: binary_sensor.prusa_printing
        from: 'on'
        to: 'off'
    condition:
      # to filter out prints cancelled before the end
      - condition: numeric_state
        entity_id: sensor.prusa_job_percentage
        above: 95
    action:
      - service: light.turn_on
        entity_id: light.atelier
      - delay:
          seconds: 1
      - service: notify.mobile_app_phophone
        data:
          message: 'Print finished.'
          data:
            attachment:
              content-type: jpeg
            push:
              category: camera
            entity_id: camera.3d_printers
      - service: light.turn_off
        entity_id: light.atelier
