# This plays ambient audio in the bedroom at low volume during the night
# It uses forked-daapd http://ejurgensen.github.io/forked-daapd/ as an audio server, 
# Running in docker: https://docs.linuxserver.io/images/docker-daapd
# Sound output is an Airplay speaker
# Music is "Long ambients 1 & 2" by Moby. It's free, thanks Moby! https://moby.com/la/

automation:
  - alias: play ambient audio during the night
    trigger:
      platform: state
      entity_id: input_boolean.night_time
      from: 'off'
      to: 'on'
    action:
      - service: switch.turn_on
        entity_id: switch.ambient_audio
  - alias: stop playing ambient audio after waking up
    trigger:
      platform: state
      entity_id: input_boolean.night_time
      from: 'on'
      to: 'off'
    action:
      - service: switch.turn_off
        entity_id: switch.ambient_audio

switch:
  platform: template
  switches:
    ambient_audio:
      turn_on:
        service: script.turn_on
        data: 
          entity_id: script.ambient_audio_on
      turn_off:
        service: script.turn_on
        data: 
          entity_id: script.ambient_audio_off
      value_template: "{{ is_state('media_player.forked_daapd_server', 'playing') }}"

script:
  ambient_audio_on:
    sequence:
      - condition: template
        value_template: "{{ is_state('binary_sensor.porte_chambre', 'off') }}"
      - condition: template
        value_template: "{{ not is_state('media_player.forked_daapd_server', 'playing') }}"
      - service: media_player.select_source
        data:
          entity_id: media_player.forked_daapd_server
          source: 'Clear queue'
      - service: media_player.select_source
        data:
          entity_id: media_player.forked_daapd_server
          source: 'long ambient (playlist)'
      - service: media_player.turn_on
        data:
          entity_id: media_player.forked_daapd_output_portable
      - service: media_player.volume_set
        data:
          entity_id: media_player.forked_daapd_output_portable
          volume_level: 0.2
      - service: media_player.media_play
        data:
          entity_id: media_player.forked_daapd_server
  ambient_audio_off:
    sequence:
      - service: media_player.media_stop
        data:
          entity_id: media_player.forked_daapd_server
      - service: media_player.turn_off
        data:
          entity_id: media_player.forked_daapd_output_portable
