sensor:
  # Exterior Air quality
  - platform: waqi
    token: !secret waqi_token
    locations:
      - paris
    stations:
      - paris
  # Inside Air Quality: Office taken from Xiaomi Air purifier
  - platform: template
    sensors:
      bureau_aqi:
        friendly_name: "Bureau AQI"
        value_template: "{{ states.fan.xiaomi_air_purifier_2s.attributes.aqi }}"
        icon_template: mdi:cloud
        unit_of_measurement: "AQI"
      chambre_aqi:
        friendly_name: "Chambre AQI"
        value_template: "{{ states.fan.xiaomi_air_purifier_2.attributes.aqi }}"
        icon_template: mdi:cloud
        unit_of_measurement: "AQI"

fan:
  - platform: xiaomi_miio
    name: Xiaomi Air Purifier 2
    host: 192.168.1.74
    token: !secret air_purifier_token_2
  - platform: xiaomi_miio
    name: Xiaomi Air Purifier 2S
    host: 192.168.1.137
    token: !secret air_purifier_token_2S
  - platform: xiaomi_miio
    name: Xiaomi Evaporative Humidifier cb1
    host: 192.168.1.193
    token: !secret humidifier_cb1_token

automation:
  - alias: Silence the air purifier during night time
    trigger:
      platform: state
      entity_id: input_boolean.night_time
      to: 'on'
    action:
      service: fan.set_speed
      entity_id: fan.xiaomi_air_purifier_2
      data:
        speed: silent
  - alias: Set the air purifier to auto during day time
    trigger:
      platform: state
      entity_id: input_boolean.night_time
      to: 'off'
    action:
      service: fan.set_speed
      entity_id: fan.xiaomi_air_purifier_2
      data:
        speed: auto

homeassistant:
  customize:
    fan.xiaomi_air_purifier_2:
      icon: 'mdi:air-purifier'
    fan.xiaomi_air_purifier_2s:
      icon: 'mdi:air-purifier'
    fan.xiaomi_evaporative_humidifier_cb1:
      icon: 'mdi:air-humidifier'
