sensor:
  # Exterior Air quality
  - platform: waqi
    token: !secret waqi_token
    locations:
      - paris
    stations:
      - paris

automation:
  - alias: 💨Silence the air purifier during night time
    trigger:
      platform: state
      entity_id: input_boolean.night_time
      to: 'on'
    action:
      - service: fan.set_preset_mode
        entity_id:
          - fan.xiaomi_air_purifier_2_2
          - fan.xiaomi_air_purifier_2s_2
        data:
          preset_mode: Silent
      - service: humidifier.set_mode
        entity_id: humidifier.zhimi_humidifier_cb1
        data:
          mode: Auto
  - alias: 💨Set the air purifier to auto during day time
    trigger:
      platform: state
      entity_id: input_boolean.night_time
      to: 'off'
    action:
      - service: fan.set_preset_mode
        entity_id:
          - fan.xiaomi_air_purifier_2_2
          - fan.xiaomi_air_purifier_2s_2
        data:
          preset_mode: Auto
      - service: humidifier.set_mode
        entity_id: humidifier.zhimi_humidifier_cb1
        data:
          mode: Auto
  - alias: 💧 Warm when water level is too low
    trigger:
      platform: numeric_state
      entity_id: sensor.zhimi_humidifier_cb1_water_level
      below: 15
    action:
      service: notify.main_devices
      data_template:
        title: "💧"
        message: 'Refill humidifier now'

homeassistant:
  customize:
    fan.xiaomi_air_purifier_2_2:
      icon: 'mdi:air-purifier'
    fan.xiaomi_air_purifier_2s_2:
      icon: 'mdi:air-purifier'
