sensor:
  # Exterior Air quality
  - platform: waqi
    token: !secret waqi_token
    locations:
      - paris
    stations:
      - Paris Centre, Paris
  # Inside Air Quality: Office taken from Xiaomi Air purifier
  - platform: template
    sensors:
      bureau_aqi:
        friendly_name: "Bureau AQI"
        value_template: "{{ states.fan.xiaomi_air_purifier_2s.attributes.aqi }}"
        icon_template: mdi:cloud
        unit_of_measurement: "AQI"
      chambre_aqi:
        friendly_name: "Chambre AQI"
        value_template: "{{ states.fan.xiaomi_air_purifier_2.attributes.aqi }}"
        icon_template: mdi:cloud
        unit_of_measurement: "AQI"
  # Inside Air Quality: Living Room taken from https://foobot.io
  - platform: foobot
    token: !secret foobot_token
    username: reefab@demenzia.net
    scan_interval: 1200

fan:
  - platform: xiaomi_miio
    name: Xiaomi Air Purifier 2
    host: 192.168.1.74
    token: !secret air_purifier_token_2
  - platform: xiaomi_miio
    name: Xiaomi Air Purifier 2S
    host: 192.168.1.137
    token: !secret air_purifier_token_2S

automation:
  - alias: Silence the air purifier during night time
    trigger:
      platform: state
      entity_id: cover.bedroom_velux
      from: 'open'
      to: 'close'
    action:
      service: fan.set_speed
      entity_id: fan.xiaomi_air_purifier_2
      data:
        speed: silent
  - alias: Set the air purifier to auto during day time
    trigger:
      platform: state
      entity_id: cover.bedroom_velux
      from: 'close'
      to: 'open'
    action:
      service: fan.set_speed
      entity_id: fan.xiaomi_air_purifier_2
      data:
        speed: auto

homeassistant:
  customize:
    fan.xiaomi_air_purifier_2:
      icon: 'mdi:air-purifier'
    fan.xiaomi_air_purifier_2s:
      icon: 'mdi:air-purifier'
    sensor.foobot_salon_pm25:
      friendly_name: PM 2.5
    sensor.foobot_salon_voc:
      friendly_name: COV
    sensor.foobot_salon_index:
      friendly_name: Index Pollution
    sensor.foobot_salon_temperature:
      hidden: true
    sensor.foobot_salon_co2:
      hidden: false
      friendly_name: Co2
    sensor.foobot_salon_humidity:
      hidden: true
