automation:
  - alias: 📹 Switch camera on if not home
    trigger:
      - platform: state
        entity_id: group.people
        to: 'not_home'
        for: "00:02:00"
    action:
      - service: switch.turn_off
        entity_id: switch.tapo_camera_privacy
  - alias: 📹 Switch camera off if home
    trigger:
      - platform: state
        entity_id: group.people
        to: 'home'
    action:
      - service: switch.turn_on
        entity_id: switch.tapo_camera_privacy
  - alias: 📹 Send notification on mouvement
    trigger:
      - platform: state
        entity_id: binary_sensor.tapo_camera_motion
        to: 'on'
    condition:
      - condition: state
        entity_id: group.people
        state: 'not_home'
    action:
      - service: notify.main_devices
        data:
          title: "🚨"
          message: 'Motion detected.'
          data:
            attachment:
              content-type: jpeg
            push:
              category: camera
            entity_id: camera.tapo_camera_hd
