automation:
  - alias: Switch camera on if not home
    trigger:
      - platform: state
        entity_id: group.people
        to: 'not_home'
    action:
      - service: switch.turn_off
        entity_id: switch.camera_privacy_mode
  - alias: Switch camera off if home
    trigger:
      - platform: state
        entity_id: group.people
        to: 'home'
    action:
      - service: switch.turn_on
        entity_id: switch.camera_privacy_mode

switch:
  - platform: template
    switches:
      camera_privacy_mode:
        value_template: "{{ state_attr('camera.tapo_camera_hd', 'privacy_mode') == 'on' }}"
        turn_on:
          service: tapo_control.set_privacy_mode
          data:
            entity_id: "camera.tapo_camera_hd"
            privacy_mode: "on"
        turn_off:
          service: tapo_control.set_privacy_mode
          data:
            entity_id: "camera.tapo_camera_hd"
            privacy_mode: "off"
