circadian_lighting:
  min_colortemp: 2237
  max_colortemp: 4291

switch:
  - platform: circadian_lighting
    min_brightness: 60
    max_brightness: 80
    lights_ct:
      - light.bureau
      - light.salon
      - light.mezzanine
      - light.chambre

automation:
  - alias: Switch circadian lightning back on during the day
    trigger:
      - platform: state
        entity_id: input_boolean.night_time
        from: 'on'
        to: 'off'
    action:
      - service: switch.turn_on
        entity_id: switch.circadian_lighting_circadian_lighting
