adaptive_lighting:
  - name: global
    lights:
      - light.bureau
      - light.salon
      - light.mezzanine
    min_brightness: 70
    max_brightness: 90
    min_color_temp: 2237
    max_color_temp: 4291
    sleep_brightness: 100
    sleep_rgb_or_color_temp: 'rgb_color'
    sleep_rgb_color: [255, 0, 255]
  - name: bedroom
    lights:
      - light.bedroom
    min_brightness: 60
    max_brightness: 100
    min_color_temp: 2237
    max_color_temp: 4291
    transition: 0

automation:
  - alias: Switch circadian lightning back on during the day
    trigger:
      - platform: state
        entity_id: input_boolean.night_time
        to: 'off'
    action:
      - service: switch.turn_on
        entity_id:
          - switch.adaptive_lighting_global
          - switch.adaptive_lighting_bedroom
