adaptive_lighting:
  - name: global
    lights:
      - light.bureau
      - light.salon
      - light.mezzanine
    min_brightness: 70
    max_brightness: 90
    min_color_temp: 2237
    max_color_temp: 4291
    sleep_brightness: 100
    sleep_rgb_or_color_temp: 'rgb_color'
    sleep_rgb_color: [255, 0, 255]
    take_over_control: false
  - name: desk
    lights:
      - light.yeelight_lamp15_0x1b3619c6
    min_brightness: 10
    max_brightness: 60
    min_color_temp: 2237
    max_color_temp: 4291
    take_over_control: false
  - name: bedroom
    lights:
      - light.chambre
    min_brightness: 60
    max_brightness: 100
    min_color_temp: 2237
    max_color_temp: 4291
    sleep_brightness: 20
    take_over_control: false

automation:
  - alias: 💡Switch circadian lightning back on during the day
    trigger:
      - platform: state
        entity_id: input_boolean.night_time
        to: 'off'
    action:
      - service: switch.turn_off
        entity_id:
          - switch.adaptive_lighting_sleep_mode_global
          - switch.adaptive_lighting_sleep_mode_bedroom
  - alias: 💡Switch circadian lightning sleep mode at night
    trigger:
      - platform: state
        entity_id: input_boolean.night_time
        to: 'on'
    action:
      - service: switch.turn_on
        entity_id:
          - switch.adaptive_lighting_sleep_mode_bedroom
