input_boolean:
  menage_mode:

switch:
  - platform: template
    switches:
      # When cleaning, switch all lights on to cool white at max
      menage:
        friendly_name: "mode ménage"
        value_template: "{{ is_state('input_boolean.menage_mode', 'on') }}"
        turn_on:
          - service: input_boolean.turn_on
            entity_id: input_boolean.menage_mode
          - service: switch.turn_off
            entity_id: switch.adaptive_lighting_global
          - delay:
              seconds: 1
          - service: light.turn_on
            entity_id: light.all_but_bedroom
            data:
              kelvin: 4291
              brightness: 255
        turn_off:
          - service: input_boolean.turn_off
            entity_id: input_boolean.menage_mode
          - service: switch.turn_on
            entity_id: switch.adaptive_lighting_global
          - delay:
              seconds: 1
          - service: light.turn_off
            entity_id: light.all_but_bedroom
          - delay:
              seconds: 1
          - service: light.turn_on
            entity_id: [light.salon, light.bureau]
            data:
              brightness: 150

homeassistant:
  customize:
    switch.menage:
      icon: 'mdi:spray-bottle'
