automation:
  - alias: Turn heating down when people are not here
    trigger:
      - platform: state
        entity_id: group.people
        to: 'not_home'
    action:
      - service: climate.set_preset_mode
        entity_id: climate.netatmo_my_room
        data:
          preset_mode: 'away'
  - alias: Turn stuff back on when there is people coming back
    trigger:
      - platform: state
        entity_id: group.people
        to: 'home'
    condition:
      - condition: state
        entity_id: binary_sensor.windows_open
        state: 'off'
    action:
      - service: climate.set_preset_mode
        entity_id: climate.netatmo_my_room
        data:
          preset_mode: "Schedule"

climate:
  - platform: netatmo

binary_sensor:
  - platform: template
    sensors:
      windows_open:
        value_template: "{{ is_state('binary_sensor.fenetre_bureau', 'on') or
                            is_state('binary_sensor.fenetre_salon', 'on') }}"

homeassistant:
  customize:
    climate.chambre:
      icon: 'mdi:radiator'
    sensor.netatmo_chambre_co2:
      friendly_name: Co2
      icon: mdi:molecule-co2
    sensor.netatmo_chambre_humidity:
      friendly_name: Humidité
    sensor.netatmo_chambre_temperature:
      friendly_name: Temperature
    sensor.netatmo_dehors_humidity:
      friendly_name: Humidité
    sensor.netatmo_dehors_temperature:
      friendly_name: Temperature
    sensor.netatmo_bureau_noise:
      friendly_name: Bruit
    sensor.netatmo_bureau_co2:
      friendly_name: Co2
      icon: mdi:molecule-co2
    sensor.netatmo_bureau_humidity:
      friendly_name: Humidité
    sensor.netatmo_bureau_temperature:
      friendly_name: Temperature
    sensor.bureau_aqi:
      friendly_name: AQI
    sensor.netatmo_salon_co2:
      friendly_name: Co2
      icon: mdi:molecule-co2
    sensor.netatmo_salon_humidity:
      friendly_name: Humidité
    sensor.netatmo_salon_temperature:
      friendly_name: Temperature
    climate.netatmo_my_room:
      friendly_name: Chaudière
