automation:
  - alias: Close covers at night
    initial_state: true
    trigger:
      platform: sun
      event: sunset
    action:
      service: cover.close_cover
      entity_id: [cover.velux_mezzanine, cover.bedroom_velux]

  - alias: Open mezzanine cover during the day
    initial_state: true
    trigger:
      platform: sun
      event: sunrise
    condition:
      - condition: state
        entity_id: group.guests
        state: 'not_home'
      - condition: numeric_state
        entity_id: sensor.dark_sky_daytime_high_apparent_temperature_0d
        below: 25
    action:
      service: cover.open_cover
      entity_id: cover.velux_mezzanine

  - alias: Open bedroom cover during the day
    initial_state: true
    trigger:
      platform: sun
      event: sunrise
    condition:
      - condition: state
        entity_id: group.people
        state: 'not_home'
      - condition: numeric_state
        entity_id: sensor.dark_sky_daytime_high_apparent_temperature_0d
        below: 25
    action:
      service: cover.open_cover
      entity_id: cover.bedroom_velux

  - alias: Toggle bedroom cover
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        id: bouton_lit
        event: 1005
    action:
      service: cover.toggle
      entity_id: cover.bedroom_velux

  - alias: Open office cover
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_open_close_switch
        event: 1002
    action:
      service: cover.open_cover
      entity_id: cover.store_bureau
  - alias: Close office cover
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_open_close_switch
        event: 2002
    action:
      service: cover.close_cover
      entity_id: cover.store_bureau


cover:
  # Custom device for controlling velux exterior blinds:
  # https://github.com/reefab/homeassistant-velux
  - platform: mqtt
    name: "Velux Mezzanine"
    command_topic: "cmnd/velux/Backlog"
    payload_open: "power2 off; power1 on; delay 1500"
    payload_close: "power1 off; power2 on; delay 320"
    payload_stop: "power1 off; power2 off"
    availability_topic: "tele/velux/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: template
    covers:
      office_blind:  # Template over Ikea blinds controlled via deconz because it doesn't remember its position
        friendly_name: "Store Bureau"
        optimistic: true
        open_cover:
          service: cover.open_cover
          data:
            entity_id: cover.store_bureau
        close_cover:
          service: cover.close_cover
          data:
            entity_id: cover.store_bureau
        set_cover_position:
          service: cover.set_cover_position
          data_template:
            entity_id: cover.store_bureau
            position: "{{position}}"
        stop_cover:
          service: cover.stop_cover
          data:
            entity_id: cover.store_bureau

      bedroom_velux:  # Using a Broadlink IR Mini to control old style velux interior blinds via IR
        friendly_name: "Store Chambre"
        optimistic: true
        open_cover:
          service: remote.send_command
          data:
            entity_id: remote.ir_bedroom_remote
            command:
              - b64:JgBkAA0qDSonDwwrDCooDwwqDSoMKg0qKA4pDigOKA4MKygODCsLLCgOKA4oDwsrDSoLAANaDSoNKigODCsMKigPCysNKgwqDSooDikOKA4nDwwrKA4NKgwrKA4oDigPCysNKgwADQUAAAAA
              - b64:JgBkAA0qDSonDwwrDCooDwwqDSoMKg0qKA4pDigOKA4MKygODCsLLCgOKA4oDwsrDSoLAANaDSoNKigODCsMKigPCysNKgwqDSooDikOKA4nDwwrKA4NKgwrKA4oDigPCysNKgwADQUAAAAA
              - b64:JgBkAA0qDSonDwwrDCooDwwqDSoMKg0qKA4pDigOKA4MKygODCsLLCgOKA4oDwsrDSoLAANaDSoNKigODCsMKigPCysNKgwqDSooDikOKA4nDwwrKA4NKgwrKA4oDigPCysNKgwADQUAAAAA
              - b64:JgBkAA0qDSonDwwrDCooDwwqDSoMKg0qKA4pDigOKA4MKygODCsLLCgOKA4oDwsrDSoLAANaDSoNKigODCsMKigPCysNKgwqDSooDikOKA4nDwwrKA4NKgwrKA4oDigPCysNKgwADQUAAAAA
              - b64:JgBkAA0qDSonDwwrDCooDwwqDSoMKg0qKA4pDigOKA4MKygODCsLLCgOKA4oDwsrDSoLAANaDSoNKigODCsMKigPCysNKgwqDSooDikOKA4nDwwrKA4NKgwrKA4oDigPCysNKgwADQUAAAAA
        close_cover:
          service: remote.send_command
          data:
            entity_id: remote.ir_bedroom_remote
            command:
              - b64:JgBkAA4pKQ0pDg0pDikpDQ4pDSkOKQ4pKQ0pDSoNKQ0OKCoNDigOKSoMKg0pDSoMDikqAAM7DikqDCoNDigOKSoMDikOKQ0pDikpDSoMKg0pDQ4pKQ0OKQ4oKg0pDSoMKg0OKCoADQUAAAAA
              - b64:JgBkAA4pKQ0pDg0pDikpDQ4pDSkOKQ4pKQ0pDSoNKQ0OKCoNDigOKSoMKg0pDSoMDikqAAM7DikqDCoNDigOKSoMDikOKQ0pDikpDSoMKg0pDQ4pKQ0OKQ4oKg0pDSoMKg0OKCoADQUAAAAA
              - b64:JgBkAA4pKQ0pDg0pDikpDQ4pDSkOKQ4pKQ0pDSoNKQ0OKCoNDigOKSoMKg0pDSoMDikqAAM7DikqDCoNDigOKSoMDikOKQ0pDikpDSoMKg0pDQ4pKQ0OKQ4oKg0pDSoMKg0OKCoADQUAAAAA
              - b64:JgBkAA4pKQ0pDg0pDikpDQ4pDSkOKQ4pKQ0pDSoNKQ0OKCoNDigOKSoMKg0pDSoMDikqAAM7DikqDCoNDigOKSoMDikOKQ0pDikpDSoMKg0pDQ4pKQ0OKQ4oKg0pDSoMKg0OKCoADQUAAAAA
              - b64:JgBkAA4pKQ0pDg0pDikpDQ4pDSkOKQ4pKQ0pDSoNKQ0OKCoNDigOKSoMKg0pDSoMDikqAAM7DikqDCoNDigOKSoMDikOKQ0pDikpDSoMKg0pDQ4pKQ0OKQ4oKg0pDSoMKg0OKCoADQUAAAAA
        stop_cover:
          service: remote.send_command
          data:
            entity_id: remote.ir_bedroom_remote
            command:
              - b64:JgBkACoNDSkqDQ0pDikpDQ4pDigOKQ4pKQ0pDSoNKQ0OKCoNDigOKSoMKg0OKA4pKgwOAANYKgwOKSoMDikOKSkNDigPKA4pDigqDSkNKgwqDQ4oKg0OKA4pKQ0qDA4pDikpDQ4ADQUAAAAA
              - b64:JgBkACoNDSkqDQ0pDikpDQ4pDigOKQ4pKQ0pDSoNKQ0OKCoNDigOKSoMKg0OKA4pKgwOAANYKgwOKSoMDikOKSkNDigPKA4pDigqDSkNKgwqDQ4oKg0OKA4pKQ0qDA4pDikpDQ4ADQUAAAAA
              - b64:JgBkACoNDSkqDQ0pDikpDQ4pDigOKQ4pKQ0pDSoNKQ0OKCoNDigOKSoMKg0OKA4pKgwOAANYKgwOKSoMDikOKSkNDigPKA4pDigqDSkNKgwqDQ4oKg0OKA4pKQ0qDA4pDikpDQ4ADQUAAAAA
              - b64:JgBkACoNDSkqDQ0pDikpDQ4pDigOKQ4pKQ0pDSoNKQ0OKCoNDigOKSoMKg0OKA4pKgwOAANYKgwOKSoMDikOKSkNDigPKA4pDigqDSkNKgwqDQ4oKg0OKA4pKQ0qDA4pDikpDQ4ADQUAAAAA
              - b64:JgBkACoNDSkqDQ0pDikpDQ4pDigOKQ4pKQ0pDSoNKQ0OKCoNDigOKSoMKg0OKA4pKgwOAANYKgwOKSoMDikOKSkNDigPKA4pDigqDSkNKgwqDQ4oKg0OKA4pKQ0qDA4pDikpDQ4ADQUAAAAA

homeassistant:
  customize:
    cover.bedroom_velux:
      device_class: 'blind'
    cover.velux_mezzanine:
      device_class: 'blind'
    cover.office_blind:
      device_class: 'blind'
