automation:
  - alias: 🪟  Close covers at night
    trigger:
      platform: sun
      event: sunset
      offset: '00:30:00'
    action:
      - service: cover.close_cover
        entity_id:
          - cover.bedroom_blind
      - condition: state
        entity_id: binary_sensor.windows_open
        state: 'off'
      - service: cover.close_cover
        entity_id:
          - cover.windows
          - cover.velux_mezzanine

  - alias: 🪟  Open mains rooms covers during the day
    trigger:
      platform: sun
      event: sunrise
    condition:
      - condition: state
        entity_id: group.guests
        state: 'not_home'
    action:
      - wait_template: "{{ is_state_attr('sensor.lightlevel_70', 'daylight', True) }}"
      - condition: state
        entity_id: binary_sensor.windows_open
        state: 'off'
      - service: cover.open_cover
        entity_id:
          - cover.windows
          - cover.velux_mezzanine

  - alias: 🪟  Open bedroom cover during the day
    trigger:
      platform: sun
      event: sunrise
    condition:
      - condition: state
        entity_id: group.people
        state: 'not_home'
      - condition: numeric_state
        entity_id: sensor.dark_sky_daytime_high_apparent_temperature_0d
        below: 25
    action:
      service: cover.open_cover
      entity_id: cover.bedroom_blind

  - alias: 🪟  Toggle bedroom cover
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        id: bouton_lit
        event: 1005
    action:
      service: cover.toggle
      entity_id: cover.bedroom_blind

  - alias: 🪟  Open office cover with switch
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_open_close_switch_2
        event: 1002
    action:
      service: cover.open_cover
      entity_id: cover.office_blind
  - alias: 🪟  Close office cover with switch
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_open_close_switch_2
        event: 2002
    action:
      service: cover.close_cover
      entity_id: cover.office_blind

  - alias: 🪟  Open living room blind with switch
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: tradfri_open_close_switch
          event: 1002
      - platform: event
        event_type: deconz_event
        event_data:
          id: tradfri_remote_control
          event: 2002
    action:
      service: cover.open_cover
      entity_id: cover.living_room_blind
  - alias: 🪟  Close living room blind with switch
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: tradfri_open_close_switch
          event: 2002
      - platform: event
        event_type: deconz_event
        event_data:
          id: tradfri_remote_control
          event: 3002
    action:
      service: cover.close_cover
      entity_id: cover.living_room_blind

  - alias: 🪟  Close window blinds when it's too bright
    trigger:
      - platform: numeric_state
        entity_id: sensor.lightlevel_70
        above: 20000
        for:
          minutes: 2
    condition:
      - condition: state
        entity_id: binary_sensor.windows_open
        state: 'off'
      - condition: numeric_state
        entity_id: sensor.netatmo_mezon_bureau_dehors_temperature
        above: 20
    action:
      - service: cover.close_cover
        entity_id: cover.skylights
      - service: cover.set_cover_position
        entity_id: cover.office_blind
        data:
          position: 0
      - service: cover.set_cover_position
        entity_id: cover.living_room_blind
        data:
          position: 50

  - alias: 🪟  Halfway close window blinds when it's sunny
    trigger:
      - platform: numeric_state
        entity_id: sensor.lightlevel_70
        below: 20000
        above: 10000
        for:
          minutes: 2
    condition:
      - condition: state
        entity_id: binary_sensor.windows_open
        state: 'off'
      - condition: numeric_state
        entity_id: sensor.netatmo_mezon_bureau_dehors_temperature
        above: 20
    action:
      - service: cover.set_cover_position
        entity_id: cover.office_blind
        data:
          position: 50
      - service: cover.set_cover_position
        entity_id: cover.living_room_blind
        data:
          position: 75

  - alias: 🪟  Re-open windows when it gets darker
    trigger:
      - platform: numeric_state
        entity_id: sensor.lightlevel_70
        below: 10000
        for:
          minutes: 2
    condition:
      - condition: state
        entity_id: binary_sensor.windows_open
        state: 'off'
    action:
      - service: cover.set_cover_position
        entity_id: cover.windows
        data:
          position: 100
      - service: cover.open_cover
        entity_id: cover.velux_mezzanine
      # - condition: state
      #   entity_id: binary_sensor.porte_chambre
      #   state: 'off'
      # - service: cover.open_cover
      #   entity_id: cover.bedroom_blind

cover:
  - platform: template
    covers:
      bedroom_blind:  # Using a Broadlink IR Mini to control old style velux interior blinds via IR
        friendly_name: "Store Chambre"
        optimistic: true
        open_cover:
          service: remote.send_command
          target:
            entity_id: remote.bedroom_remote_remote
          data:
            device: velux
            num_repeats: 5
            command: up
        close_cover:
          service: remote.send_command
          target:
            entity_id: remote.bedroom_remote_remote
          data:
            device: velux
            num_repeats: 5
            command: down
        stop_cover:
          service: remote.send_command
          target:
            entity_id: remote.bedroom_remote_remote
          data:
            device: velux
            num_repeats: 5
            command: stop
      office_blind:
        friendly_name: "Store Bureau"
        device_class: 'blind'
        position_template: "{{ state_attr('cover.store_bureau', 'current_position') }}"
        open_cover:
          service: cover.set_cover_position
          entity_id: cover.store_bureau
          data:
            position: 100
        close_cover:
          service: cover.set_cover_position
          entity_id: cover.store_bureau
          data:
            position: 0
        set_cover_position:
          service: cover.set_cover_position
          entity_id: cover.store_bureau
          data:
            position: "{{position}}"
      living_room_blind:
        friendly_name: "Store Salon"
        device_class: 'blind'
        position_template: "{{ state_attr('cover.window_covering_device_2S', 'current_position') }}"
        open_cover:
          service: cover.set_cover_position
          entity_id: cover.window_covering_device_2S
          data:
            position: 100
        close_cover:
          service: cover.set_cover_position
          entity_id: cover.window_covering_device_2S
          data:
            position: 0
        set_cover_position:
          service: cover.set_cover_position
          entity_id: cover.window_covering_device_2S
          data:
            position: "{{position}}"
  - platform: group
    name: windows
    entities:
      - cover.living_room_blind
      - cover.office_blind
  - platform: group
    name: skylights
    entities:
      - cover.velux_mezzanine
      - cover.bedroom_blind

homeassistant:
  customize:
    cover.bedroom_blind:
      device_class: 'blind'
      friendly_name: "Store Chambre"
    cover.velux_mezzanine:
      device_class: 'blind'
      friendly_name: "Store Mezzanine"
