deconz:
  host: deconz
  port: 80
  api_key: !secret deconz_api

homeassistant:
  customize:
    sensor.cuisine:
      friendly_name: Temperature Cuisine
    sensor.cuisine_2:
      friendly_name: Humidité Cuisine
    sensor.cuisine_3:
      friendly_name: Pression Cuisine
    sensor.salle_de_bain:
      friendly_name: Temperature Sdb
    sensor.salle_de_bain_3:
      friendly_name: Humidité Sdb
    sensor.salle_de_bain_2:
      friendly_name: Pression Sdb
    sensor.temperature_50:
      friendly_name: Temperature Mezzanine
    sensor.humidity_51:
      friendly_name: Humidité Mezzanine
    binary_sensor.lumi_sensor_smoke_2:
      friendly_name: Fumée Bureau
    binary_sensor.lumi_sensor_smoke:
      friendly_name: Fumée Salon
    binary_sensor.robinet_toilette:
      icon: mdi:toilet
    binary_sensor.porte_entree:
      icon: mdi:door
    binary_sensor.porte_chambre:
      icon: mdi:door
    binary_sensor.fenetre_salon:
      icon: mdi:window-closed
    binary_sensor.fenetre_bureau:
      icon: mdi:window-closed
    binary_sensor.compteur_eau:
      icon: mdi:pipe-leak
    binary_sensor.buanderie:
      icon: mdi:washing-machine
    switch.on_off_plug_in_unit_20:
      friendly_name: Alimentation Imprimantes 3D
