# Doorbell zigbee sensor Echostar by Hughes
automation:
  - alias: 🛎 Send notification when doorbell is rung
    trigger:
      - platform: state
        entity_id: sensor.doorbell_1_action
        to: bell1
    action:
      - service: notify.main_devices
        data_template:
          title: "🛎"
          message: 'Ding!'
          data:
            push:
              thread-id: 'doorbell-notification-group'
            apns_headers:
              'apns-collapse-id': 'doorbell-notification-group'
      - service: notify.steambox
        data:
          title: "🛎"
          message: 'Ding!'
