automation:
  # auto switch off when it's cool enough
  - alias: 🆒 turn office fan off automatically
    trigger:
      - below: '25'
        entity_id: sensor.netatmo_mezon_bureau_temperature
        platform: numeric_state
    condition:
      - condition: state
        entity_id: fan.ventilateur_bureau
        state: 'on'
    action:
      - service: fan.turn_off
        entity_id: fan.ventilateur_bureau

  - alias: 🆒 Switch fans off if no one is home
    trigger:
      - platform: state
        entity_id: group.people
        from: 'home'
        to: 'not_home'
        for: "00:02:00"
    action:
      - service: fan.turn_off
        entity_id:
          - fan.ventilateur_bureau
          - fan.dmaker_fan_1c
          - fan.ventilateur_bois
          - fan.mi_smart_standing_fan_2_lite2
          - fan.mi_smart_standing_fan_2_lite3

  - alias: 🆒 Switch fans off at night time
    trigger:
      platform: state
      entity_id: input_boolean.night_time
      to: 'on'
    action:
      - service: fan.turn_off
        entity_id:
          - fan.ventilateur_bureau
          - fan.dmaker_fan_1c
          - fan.mi_smart_standing_fan_2_lite2
