automation:
  # auto switch off when it's cool enough
  - alias: 🆒 turn office fan off automatically
    trigger:
      - below: '25'
        entity_id: sensor.netatmo_mezon_bureau_temperature
        platform: numeric_state
    condition:
      - condition: state
        entity_id: fan.ventilateur_bureau
        state: 'on'
    action:
      - entity_id: fan.ventilateur_bureau
        service: fan.set_speed
        data:
          speed: 'off'
  - alias: 🆒 Switch fans off if no one is home
    trigger:
      - platform: state
        entity_id: group.people
        from: 'home'
        to: 'not_home'
        for:
          minutes: 2
    action:
      - service: fan.turn_off
        entity_id:
          - fan.ventilateur_bureau
          - fan.xiaomi_smart_standing_fan
          - fan.black_fan
          - fan.ventilateur_bois

  - alias: 🆒 Switch fans off at night time
    trigger:
      platform: state
      entity_id: input_boolean.night_time
      to: 'on'
    action:
      - service: fan.turn_off
        entity_id:
          - fan.ventilateur_bureau
          - fan.xiaomi_smart_standing_fan

fan:
  - platform: xiaomi_miio_fan
    name: Xiaomi Smart Standing fan
    host: 192.168.1.63
    token: 21f6d771728ebc67ce53a182df0f7a85
