automation:
  - alias: Toggle bed fan
    trigger:
      platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d0001bf6e86
        click_type: single
    action:
      service: fan.toggle
      entity_id: fan.petit_ventilateur
  - alias: turn office fan on
    initial_state: false
    trigger:
      - entity_id: device_tracker.imac
        from: not home
        platform: state
        to: home
      - above: '26'
        entity_id: sensor.netatmo_bureau_temperature
        platform: numeric_state
    condition:
      - above: '26'
        condition: numeric_state
        entity_id: sensor.netatmo_bureau_temperature
    action:
      - entity_id: fan.ventilateur_bureau
        service: fan.turn_on
  # auto switch off when it's cool enough
  - alias: turn office fan off
    trigger:
      - entity_id: device_tracker.imac
        from: home
        platform: state
        to: not home
      - below: '26'
        entity_id: sensor.netatmo_bureau_temperature
        platform: numeric_state
    condition:
      - condition: state
        entity_id: fan.ventilateur_bureau
        state: 'on'
    action:
      - entity_id: fan.ventilateur_bureau
        service: fan.turn_off
  - alias: toggle fans with cube
    trigger:
      platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.cube_158d000104d0ed_2
        action_type: tap_twice
    action:
      - service: fan.toggle
        entity_id: fan.ventilateur_bois

fan:
  # All those fans are controlled using sonoff basic switches
  - platform: mqtt
    name: "Ventilateur bureau"
    command_topic: "cmnd/office_fan/FanSpeed"
    speed_state_topic: "stat/office_fan/RESULT"
    speed_command_topic: "cmnd/office_fan/FanSpeed"
    speed_value_template: "{{ value_json.FanSpeed }}"
    availability_topic: "tele/office_fan/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    state_topic: "stat/office_fan/RESULT"
    state_value_template: >
      {% if value_json.FanSpeed is defined %}
        {% if value_json.FanSpeed == 0 -%}0{%- elif value_json.FanSpeed > 0 -%}4{%- endif %}
      {% else %}
        {% if states.fan.master_bedroom_fan.state == 'off' -%}0{%- elif states.fan.master_bedroom_fan.state == 'on' -%}4{%- endif %}
      {% endif %}
    qos: 1
    payload_off: "0"
    payload_on: "1"
    payload_low_speed: "1"
    payload_medium_speed: "2"
    payload_high_speed: "3"
    retain: true
    speeds:
      - off
      - low
      - medium
      - high
  - platform: mqtt
    name: "Petit ventilateur"
    state_topic: "stat/black_fan/POWER"
    command_topic: "cmnd/black_fan/POWER"
    availability_topic: "tele/black_fan/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
  - platform: mqtt
    name: "Ventilateur bois"
    state_topic: "stat/wood_fan/POWER"
    command_topic: "cmnd/wood_fan/POWER"
    availability_topic: "tele/wood_fan/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

homeassistant:
  customize:
    automation.toggle_bed_fan:
      hidden: true
