automation:
  - alias: Toggle bed fan
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        id: bouton_lit
        event: 1003
    action:
      service: fan.toggle
      entity_id: fan.petit_ventilateur
  # auto switch off when it's cool enough
  - alias: turn office fan off
    trigger:
      - entity_id: device_tracker.imac
        from: home
        platform: state
        to: not home
      - below: '26'
        entity_id: sensor.netatmo_bureau_temperature
        platform: numeric_state
    condition:
      - condition: state
        entity_id: fan.ventilateur_bureau
        state: 'on'
    action:
      - entity_id: fan.ventilateur_bureau
        service: fan.set_speed
        data:
          speed: 'off'
  - alias: toggle fans with cube
    trigger:
      platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.cube_158d000104d0ed_2
        action_type: tap_twice
    action:
      - service: fan.toggle
        entity_id: fan.ventilateur_bois

fan:
  # Sonoff iFan02 with Tasmota
  # https://github.com/arendst/Sonoff-Tasmota/wiki/Sonoff-iFan02
  - platform: mqtt
    name: "Ventilateur bureau"
    command_topic: "cmnd/office_fan/FanSpeed"
    speed_command_topic: "cmnd/office_fan/FanSpeed"
    state_topic: "stat/office_fan/RESULT"
    speed_state_topic: "stat/office_fan/RESULT"
    state_value_template: >
      {% if value_json.FanSpeed is defined %}
        {% if value_json.FanSpeed == 0 -%}0{%- elif value_json.FanSpeed > 0 -%}1{%- endif %}
      {% else %}
        {% if states.fan.ventilateur_bureau.state == 'off' -%}0{%- elif states.fan.ventilateur_bureau.state == 'on' -%}1{%- endif %}
      {% endif %}
    speed_value_template: "{{ value_json.FanSpeed }}"
    availability_topic: tele/office_fan/LWT
    payload_off: "0"
    payload_on: "1"
    payload_low_speed: "1"
    payload_medium_speed: "2"
    payload_high_speed: "3"
    payload_available: Online
    payload_not_available: Offline
    speeds:
      - 'off'
      - low
      - medium
      - high
  # Sonoff Basic with Tasmota
  - platform: mqtt
    name: "Petit ventilateur"
    state_topic: "stat/black_fan/POWER"
    command_topic: "cmnd/black_fan/POWER"
    availability_topic: "tele/black_fan/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
  # Sonoff Basic with Tasmota
  - platform: mqtt
    name: "Ventilateur Bois"
    state_topic: "stat/salon_fan/POWER"
    command_topic: "cmnd/salon_fan/POWER"
    availability_topic: "tele/salon_fan/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

homeassistant:
  customize:
    automation.toggle_bed_fan:
      hidden: true
