automation:
  - alias: 🆒 Toggle bed fan
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        id: bouton_lit
        event: 1003
    action:
      service: fan.toggle
      entity_id: fan.petit_ventilateur
  - alias: 🆒 turn on office fan
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_on_off_switch
        event: 1003
    action:
      service: fan.set_speed
      entity_id: fan.ventilateur_bureau
      data:
         speed: 'low'
  - alias: 🆒 turn off office fan
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_on_off_switch
        event: 2003
    action:
      service: fan.set_speed
      entity_id: fan.ventilateur_bureau
      data:
         speed: 'off'
  # auto switch off when it's cool enough
  - alias: 🆒 turn office fan off
    trigger:
      - below: '25'
        entity_id: sensor.netatmo_mezon_bureau_temperature
        platform: numeric_state
    condition:
      - condition: state
        entity_id: fan.ventilateur_bureau
        state: 'on'
    action:
      - entity_id: fan.ventilateur_bureau
        service: fan.set_speed
        data:
          speed: 'off'
  - alias: 🆒 Switch fans off if no one is home
    trigger:
      - platform: state
        entity_id: group.people
        from: 'home'
        to: 'not_home'
        for:
          minutes: 2
    action:
      - service: fan.turn_off
        entity_id:
          - fan.ventilateur_bureau
          - fan.xiaomi_smart_standing_fan
          - fan.petit_ventilateur

  - alias: 🆒 Switch fans off at night time
    trigger:
      platform: state
      entity_id: input_boolean.night_time
      to: 'on'
    action:
      - service: fan.turn_off
        entity_id:
          - fan.ventilateur_bureau
          - fan.xiaomi_smart_standing_fan

fan:
  # Sonoff iFan02 with Tasmota
  # https://github.com/arendst/Sonoff-Tasmota/wiki/Sonoff-iFan02
  - platform: mqtt
    name: "Ventilateur bureau"
    command_topic: "cmnd/office_fan/FanSpeed"
    state_topic: "stat/office_fan/RESULT"
    state_value_template: >
      {% if value_json.FanSpeed is defined %}
        {% if value_json.FanSpeed == 0 -%}0{%- elif value_json.FanSpeed > 0 -%}1{%- endif %}
      {% else %}
        {% if states.fan.ventilateur_bureau.state == 'off' -%}0{%- elif states.fan.ventilateur_bureau.state == 'on' -%}1{%- endif %}
      {% endif %}
    percentage_value_template: "{{ value_json.FanSpeed }}"
    percentage_state_topic: "stat/office_fan/RESULT"
    percentage_command_topic: "cmnd/office_fan/FanSpeed"
    availability_topic: tele/office_fan/LWT
    payload_off: "0"
    payload_on: "1"
    speed_range_min: 1
    speed_range_max: 3
    payload_available: Online
    payload_not_available: Offline
  # Sonoff Basic with Tasmota
  - platform: mqtt
    name: "Petit ventilateur"
    state_topic: "stat/black_fan/POWER"
    command_topic: "cmnd/black_fan/POWER"
    availability_topic: "tele/black_fan/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    payload_on: "ON"
    payload_off: "OFF"
  - platform: xiaomi_miio_fan
    name: Xiaomi Smart Standing fan
    host: 192.168.1.63
    token: 21f6d771728ebc67ce53a182df0f7a85
