sensor:
  # Power metering using a belkin insight plug
  - platform: template
    sensors:
      fridge_power:
        friendly_name: Fridge power
        unit_of_measurement: 'W'
        value_template: "{{state_attr('switch.radiateur_lit', 'current_power_w')}}"

homeassistant:
  customize:
    sensor.fridge_power:
      icon: 'mdi:fridge'
