sensor:
  # Power metering using a belkin insight plug
  - platform: template
    sensors:
      fridge_power:
        friendly_name: Fridge power
        unit_of_measurement: 'w'
        value_template: "{{states.switch.radiateur_lit.attributes.current_power_w}}"

homeassistant:
  customize:
    sensor.fridge_power:
      icon: 'mdi:fridge'
