automation:
  - alias: switch entrance light on door opening
    trigger:
      - platform: state
        entity_id: binary_sensor.porte_entree
        from: 'off'
        to: 'on'
    action:
      service: light.turn_on
      entity_id: light.entree_2

  # Those replaces the 'presence based light' component but have the advantage
  # of being able to be enabled/disabled on demand
  - alias: Switch lights off if no one is home
    trigger:
      - platform: state
        entity_id: group.people
        from: 'home'
        to: 'not_home'
        for:
          minutes: 2
    action:
      - service: light.turn_off
        entity_id: group.all_lights
  - alias: Switch lights on if people are coming home
    trigger:
      - platform: state
        entity_id: group.people
        from: 'not_home'
        to: 'home'
    condition:
      - condition: sun
        after: sunset
        after_offset: "-00:30:00"
    action:
      - service: light.turn_on
        entity_id: group.main_rooms_lights
  - alias: Switch lights on if people are home at sunset
    trigger:
      - platform: sun
        event: sunset
        offset: '-00:30:00'
    condition:
      - condition: state
        entity_id: group.people
        state: home
      - condition: state
        entity_id: switch.steambox
        state: 'off'
    action:
      - service: light.turn_on
        entity_id: group.main_rooms_lights

  - alias: Switch all lights off with button press
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        id: bouton_lit
        type: 1004
    action:
      service: scene.turn_on
      entity_id: scene.night_time

light:
  # Ikea light strips controlled using a sonoff iFan02
  - platform: mqtt
    name: Vitrine
    command_topic: "cmnd/office_fan/POWER1"
    state_topic: "stat/office_fan/POWER1"
    availability_topic: "tele/office_fan/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

homeassistant:
  customize:
    light.bureau:
      icon: 'mdi:ceiling-light'
    light.salon:
      icon: 'mdi:led-strip'
    light.vitrine:
      icon: 'mdi:led-strip'
    automation.switch_all_lights_off_with_button_press:
      hidden: true
    automation.if_there_is_motion_and_its_dark_turn_on_the_light_in_the_bathroom:
      hidden: true
    group.main_rooms_lights:
      hidden: true
