group:
  main_rooms_lights:
    name: Main Lights
    entities:
      - light.salon
      - light.bureau

automation:
  # Those replaces the 'presence based light' component but have the advantage
  # of being able to be enabled/disabled on demand
  - alias: Switch lights off if no one is home
    trigger:
      - platform: state
        entity_id: group.people
        from: 'home'
        to: 'not_home'
        for:
          minutes: 2
    action:
      - service: light.turn_off
        entity_id: all
  - alias: Switch lights on if people are coming home
    trigger:
      - platform: state
        entity_id: group.people
        from: 'not_home'
        to: 'home'
    condition:
      - condition: numeric_state
        entity_id: sun.sun
        value_template: "{{ state_attr('sun.sun', 'elevation') }}"
        below: 3.0
    action:
      - service: light.turn_on
        entity_id: group.main_rooms_lights
  - alias: Switch lights on if people are home at sunset
    trigger:
      - platform: numeric_state
        entity_id: sun.sun
        value_template: "{{ state_attr('sun.sun', 'elevation') }}"
        below: 3.0
    condition:
      - condition: state
        entity_id: group.people
        state: home
      - condition: state
        entity_id: switch.benq_w1070
        state: 'off'
    action:
      - service: light.turn_on
        entity_id: group.main_rooms_lights
  - alias: Switch lights off after sunrise
    trigger:
      - platform: numeric_state
        entity_id: sun.sun
        value_template: "{{ state_attr('sun.sun', 'elevation') }}"
        above: 3.0
    action:
      - service: light.turn_off
        entity_id: group.main_rooms_lights

  - alias: Switch all lights off with button press
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        id: bouton_lit
        event: 1004
    action:
      - service: light.turn_off
        entity_id: all
      - service: fan.turn_off
        entity_id: fan.ventilateur_bureau
      - service: fan.turn_off
        entity_id: fan.ventilateur_bois

light:
  # Ikea light strips controlled using a sonoff iFan02
  - platform: mqtt
    name: Vitrine
    command_topic: "cmnd/office_fan/POWER1"
    state_topic: "stat/office_fan/POWER1"
    availability_topic: "tele/office_fan/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    payload_on: "ON"
    payload_off: "OFF"

homeassistant:
  customize:
    light.bureau:
      icon: 'mdi:desk'
    light.salon:
      icon: 'mdi:sofa'
    light.vitrine:
      icon: 'mdi:led-strip-variant'
    light.atelier:
      icon: 'mdi:tools'
    light.mezzanine:
      icon: 'mdi:bed-double'
    light.salle_de_bain_2:
      icon: 'mdi:shower'
    light.chambre:
      icon: 'mdi:bed-queen'
    light.cuisine:
      icon: 'mdi:pot-mix'
    light.spots_salon:
      icon: 'mdi:wallpaper'
    light.dressing:
      icon: 'mdi:hanger'
    automation.switch_all_lights_off_with_button_press:
      hidden: true
    automation.if_there_is_motion_and_its_dark_turn_on_the_light_in_the_bathroom:
      hidden: true
    group.main_rooms_lights:
      hidden: true
