automation:
  - alias: turn up volume with cube
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        entity: lumi_sensor_cube_21
    condition:
      - condition: template
        value_template: '{{ trigger.event.data.event > 0 }}'
      - condition: state
        entity_id: media_player.yamaha_receiver
        state: 'on'
    action:
      - service: script.turn_on
        entity_id: script.ht_volume_up
  - alias: turn down volume with cube
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        entity: lumi_sensor_cube_21
    condition:
      - condition: template
        value_template: '{{ trigger.event.data.event < 0 }}'
      - condition: state
        entity_id: media_player.yamaha_receiver
        state: 'on'
    action:
      - service: script.turn_on
        entity_id: script.ht_volume_down
  - alias: mute volume with cube
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        entity: lumi_sensor_cube_20
        event: 7007
    condition:
      condition: state
      entity_id: media_player.yamaha_receiver
      state: 'on'
    action:
      - service: script.turn_on
        entity_id: script.ht_volume_mute

switch:
  - platform: wake_on_lan
    name: steambox
    host: 192.168.1.70
    mac: 'd8:cb:8a:35:32:af'
    broadcast_address: 192.168.1.255
    turn_off:
      service: rest_command.steambox
      data_template:
        command: 'shutdown'
  - platform: template
    switches:
      projector:
        value_template: '{{ states.switch.benq_w1070.state }}'
        turn_on:
          service: script.turn_on
          entity_id: script.projo_on
        turn_off:
          service: script.turn_on
          entity_id: script.projo_off

rest_command:
  steambox:
    # Small windows software to shut it down remotely
    url: 'http://192.168.1.70:5001/{{ command }}'

media_player:
  - platform: yamaha
    host: 192.168.1.103
  - platform: universal
    name: Écran salon
    children:
      - media_player.yamaha_receiver
    commands:
      turn_on:
        service: script.turn_on
        data:
          entity_id: script.projo_on
      turn_off:
        service: script.turn_on
        data:
          entity_id: script.projo_off
      volume_up:
        service: script.turn_on
        data:
          entity_id: script.ht_volume_up
      volume_down:
        service: script.turn_on
        data:
          entity_id: script.ht_volume_down
      volume_mute:
        service: script.turn_on
        data:
          entity_id: script.ht_volume_mute
      volume_set:
        service: media_player.volume_set
        data_template:
          entity_id: media_player.yamaha_receiver
          volume_level: '{{ volume_level }}'
      select_source:
        service: media_player.select_source
        data_template:
          entity_id: media_player.yamaha_receiver
          source: '{{ source }}'
    attributes:
      state: media_player.yamaha_receiver
      is_volume_muted: media_player.yamaha_receiver|is_volume_muted
      volume_level: media_player.yamaha_receiver|volume_level
      source: media_player.yamaha_receiver|source
      source_list: media_player.yamaha_receiver|source_list

script:
  projo_on:
    alias: Projo On
    sequence:
      - service: switch.turn_off
        entity_id: switch.circadian_lighting_circadian_lighting
      - service: light.turn_off
        entity_id: light.bureau
      - service: light.turn_on
        entity_id: light.projo
        data:
          brightness: 0
          transition: 60
      - service: light.turn_on
        entity_id: light.ecran
        data:
          brightness: 100
          transition: 60
      - service: switch.turn_on
        entity_id: switch.steambox
      - service: switch.turn_on
        entity_id: switch.benq_w1070
      - service: media_player.turn_on
        entity_id: media_player.yamaha_receiver
      - service: media_player.select_source
        entity_id: media_player.yamaha_receiver
        data:
          source: 'HDMI2'
      - delay: '00:01:00'
      - service: light.turn_off
        entity_id: light.projo

  projo_off:
    alias: Projo Off
    sequence:
      - service: switch.turn_off
        entity_id: switch.benq_w1070
      - service: media_player.turn_off
        entity_id: media_player.yamaha_receiver
      - service: switch.turn_off
        entity_id: switch.steambox
      - service: switch.turn_on
        entity_id: switch.circadian_lighting_circadian_lighting
      - condition: state
        entity_id: sun.sun
        state: 'above_horizon'
      - service: light.turn_off
        entity_id: light.ecran

  ht_volume_up:
    alias: Volume Up
    sequence:
      - service: media_player.volume_set
        entity_id: media_player.yamaha_receiver
        data_template:
          volume_level: '{{ states.media_player.yamaha_receiver.attributes.volume_level + 0.01 }}'

  ht_volume_down:
    alias: Volume Down
    sequence:
      - service: media_player.volume_set
        entity_id: media_player.yamaha_receiver
        data_template:
          volume_level: '{{ states.media_player.yamaha_receiver.attributes.volume_level - 0.01 }}'

  ht_volume_mute:
    alias: Volume Mute
    sequence:
      - service: media_player.volume_mute
        entity_id: media_player.yamaha_receiver
        data:
          is_volume_muted: true

homeassistant:
  customize:
    switch.steambox:
      icon: 'mdi:steam'
    switch.steambox_wol:
      hidden: true
    script.projo_on:
      hidden: true
    script.projo_off:
      hidden: true
    switch.projector:
      friendly-name: Projo
      icon: 'mdi:projector'
    media_player.yamaha_receiver:
      hidden: true
  customize_glob:
    "automation.*with_cube":
      hidden: true
