switch:
  - platform: template
    switches:
      projector:
        value_template: '{{ states.switch.benq_w1070.state }}'
        turn_on:
          - service: switch.turn_off
            entity_id: switch.circadian_lighting_circadian_lighting
          - service: light.turn_off
            entity_id: light.bureau
          - service: switch.turn_on
            entity_id: switch.steambox
          - service: switch.turn_on
            entity_id: switch.benq_w1070
          - service: media_player.turn_on
            entity_id: media_player.yamaha_receiver
          - service: media_player.select_source
            entity_id: media_player.yamaha_receiver
            data:
              source: 'HDMI1'
          - service: light.turn_on
            entity_id:
              - light.projo
              - light.ecran
            data:
              brightness: 0
              transition: 60
          - delay: '00:01:00'
          - service: light.turn_off
            entity_id: all
          - delay: '00:01:00'
          - service: switch.turn_on
            entity_id: switch.circadian_lighting_circadian_lighting
        turn_off:
          - service: switch.turn_off
            entity_id: switch.benq_w1070
          - service: media_player.turn_off
            entity_id: media_player.yamaha_receiver
          - service: switch.turn_off
            entity_id: switch.steambox
          - service: light.turn_off
            entity_id:
              - light.hue_ws2812_ring_1
              - light.hue_ws2812_ring_2
          - condition: state
            entity_id: sun.sun
            state: 'below_horizon'
          - service: light.turn_on
            entity_id: light.salon
            data:
              transition: 60

media_player:
  - platform: universal
    name: Écran salon
    children:
      - media_player.yamaha_receiver
    commands:
      turn_on:
        service: script.turn_on
        data:
          entity_id: script.projo_on
      turn_off:
        service: script.turn_on
        data:
          entity_id: script.projo_off
      volume_up:
        service: script.turn_on
        data:
          entity_id: script.ht_volume_up
      volume_down:
        service: script.turn_on
        data:
          entity_id: script.ht_volume_down
      volume_mute:
        service: script.turn_on
        data:
          entity_id: script.ht_volume_mute
      volume_set:
        service: media_player.volume_set
        data_template:
          entity_id: media_player.yamaha_receiver
          volume_level: '{{ volume_level }}'
      select_source:
        service: media_player.select_source
        data_template:
          entity_id: media_player.yamaha_receiver
          source: '{{ source }}'
    attributes:
      state: media_player.yamaha_receiver
      is_volume_muted: media_player.yamaha_receiver|is_volume_muted
      volume_level: media_player.yamaha_receiver|volume_level
      source: media_player.yamaha_receiver|source
      source_list: media_player.yamaha_receiver|source_list

homeassistant:
  customize:
    switch.projector:
      friendly-name: Projo
      icon: 'mdi:projector'
    media_player.ecran_salon:
      device_class: tv
