switch:
  - platform: template
    switches:
      projector:
        turn_on:
          - service: switch.turn_off
            entity_id: switch.adaptive_lighting_global
          - service: light.turn_off
            entity_id:
              - light.bureau
              - light.cuisine
          - service: switch.turn_on
            entity_id:
              - switch.steambox
              - switch.benq_w1070
          - service: media_player.turn_on
            entity_id: media_player.yamaha_receiver
          - service: media_player.select_source
            entity_id: media_player.yamaha_receiver
            data:
              source: 'HDMI1'
          - if:
              - condition: state
                entity_id: light.salon
                state: 'on'
            then:
              - service: light.turn_on
                entity_id: light.salon
                data:
                  brightness: 3
                  transition: 60
          - wait_for_trigger:
              - platform: state
                entity_id: button.steambox_1080p
                from: unavailable
          - delay: 30
          - service: button.press
            entity_id: button.steambox_hyperion
          - service: button.press
            entity_id: button.steambox_1080p
        turn_off:
          - service: switch.turn_off
            entity_id:
              - switch.steambox
              - switch.benq_w1070
          - service: media_player.turn_off
            entity_id: media_player.yamaha_receiver
          - if:
              - condition: state
                entity_id: binary_sensor.sun_up
                state: 'off'
            then:
              - service: light.turn_on
                entity_id: light.salon
                data:
                  brightness: 153
                  transition: 30
              - delay: 30
          - service: switch.turn_on
            entity_id: switch.adaptive_lighting_global
          - delay: 120
          - service: light.turn_on
            entity_id: light.wled
          - delay: 10
          - service: light.turn_off
            entity_id: light.wled

binary_sensor:
  - platform: rest
    name: Airport Express Airplay Status
    resource: http://localhost:8087/airport.home.arpa
    scan_interval: 30
    value_template: "{{ value_json.Status }}"

media_player:
  - platform: universal
    name: Écran salon
    children:
      - media_player.yamaha_receiver
      - media_player.steambox
    commands:
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.projector
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.projector
      volume_up:
        service: script.turn_on
        data:
          entity_id: script.ht_volume_up
      volume_down:
        service: script.turn_on
        data:
          entity_id: script.ht_volume_down
      volume_mute:
        service: script.turn_on
        data:
          entity_id: script.ht_volume_mute
      volume_set:
        service: media_player.volume_set
        data_template:
          entity_id: media_player.yamaha_receiver
          volume_level: '{{ volume_level }}'
      select_source:
        service: media_player.select_source
        data_template:
          entity_id: media_player.yamaha_receiver
          source: '{{ source }}'
      media_play:
        service: media_player.media_play
        entity_id: media_player.steambox
      media_pause:
        service: media_player.media_pause
        entity_id: media_player.steambox
      media_stop:
        service: media_player.media_stop
        entity_id: media_player.steambox
      media_next_track:
        service: media_player.media_next_track
        entity_id: media_player.steambox
      media_previous_track:
        service: media_player.media_previous_track
        entity_id: media_player.steambox
    attributes:
      state: media_player.yamaha_receiver
      is_volume_muted: media_player.yamaha_receiver|is_volume_muted
      volume_level: media_player.yamaha_receiver|volume_level
      source: media_player.yamaha_receiver|source
      source_list: media_player.yamaha_receiver|source_list

automation:
  - alias: 🎬 Play/Pause
    trigger:
      - platform: mqtt
        topic: zigbee2mqtt/remote_1/action
        payload: 'toggle'
    action:
      - service: media_player.media_play_pause
        entity_id: media_player.steambox
      - delay: 1
  - alias: 🎬 Previous
    trigger:
      - platform: mqtt
        topic: zigbee2mqtt/remote_1/action
        payload: 'track_previous'
    action:
      - service: button.press
        entity_id: button.steambox_left_arrow
      - delay: 1
  - alias: 🎬 Next
    trigger:
      - platform: mqtt
        topic: zigbee2mqtt/remote_1/action
        payload: 'track_next'
    action:
      - service: button.press
        entity_id: button.steambox_right_arrow
      - delay: 1
  - alias: 🎬 Enter
    trigger:
      - platform: mqtt
        topic: zigbee2mqtt/remote_1/action
        payload: 'dot_2_initial_press'
    action:
      - service: button.press
        entity_id: button.steambox_enter
      - delay: 1
  - alias: 🎬 Back
    trigger:
      - platform: mqtt
        topic: zigbee2mqtt/remote_1/action
        payload: 'dot_1_initial_press'
    action:
      - service: button.press
        entity_id: button.steambox_backspace
      - delay: 1
  - alias: 🎬 Bring lights on during plex pause
    trigger:
      - platform: state
        entity_id: media_player.plex_plex_media_player_steambox
        to: paused
    action:
      - condition: state
        entity_id: binary_sensor.sun_up
        state: 'off'
      - service: light.turn_on
        entity_id: light.salon
        data:
          brightness: 90
          transition: 10

  - alias: 🎬 Bring lights off after plex pause
    trigger:
      - platform: state
        entity_id: media_player.plex_plex_media_player_steambox
        from: paused
    action:
      - service: light.turn_off
        entity_id: light.cuisine
      - condition: state
        entity_id: binary_sensor.sun_up
        state: 'off'
      - service: light.turn_on
        entity_id: light.salon
        data:
          brightness: 3
          transition: 10

homeassistant:
  customize:
    switch.projector:
      friendly-name: Projecteur
      icon: 'mdi:projector'
    media_player.ecran_salon:
      friendly-name: Projecteur
      device_class: tv
