switch:
  - platform: template
    switches:
      projector:
        value_template: '{{ states.switch.benq_w1070.state }}'
        turn_on:
          - service: switch.turn_off
            entity_id: switch.adaptive_lighting_global
          - service: light.turn_off
            entity_id:
              - light.bureau
              - light.cuisine
          - service: switch.turn_on
            entity_id: switch.steambox
          - service: switch.turn_on
            entity_id: switch.benq_w1070
          - service: media_player.turn_on
            entity_id: media_player.yamaha_receiver
          - service: media_player.select_source
            entity_id: media_player.yamaha_receiver
            data:
              source: 'HDMI1'
          - choose:
              - conditions:
                  - condition: state
                    entity_id: light.salon
                    state: 'on'
                sequence:
                  - service: light.turn_on
                    entity_id: light.salon
                    data:
                      brightness: 3
                      transition: 60
          - wait_for_trigger:
              - platform: state
                entity_id: button.steambox_1080p
                from: unavailable
          - service: button.press
            entity_id: button.steambox_1080p
          - wait_for_trigger:
              - platform: state
                entity_id: button.steambox_hyperion
                from: unavailable
          - service: button.press
            entity_id: button.steambox_hyperion
          - wait_for_trigger:
              - platform: state
                entity_id: light.first_led_hardware_instance
                from: unavailable
          - service: switch.turn_on
            entity_id:
              - switch.first_led_hardware_instance_component_platform_capture
              - switch.first_led_hardware_instance_component_led_device
        turn_off:
          - service: switch.turn_off
            entity_id:
              - switch.first_led_hardware_instance_component_platform_capture
              - switch.first_led_hardware_instance_component_led_device
              - switch.steambox
              - switch.benq_w1070
          - delay: 5
          - service: switch.turn_off
            entity_id: switch.steambox
          - service: media_player.turn_off
            entity_id: media_player.yamaha_receiver
          - choose:
              - conditions:
                  - condition: state
                    entity_id: binary_sensor.sun_up
                    state: 'off'
                sequence:
                  - service: light.turn_on
                    entity_id: light.salon
                    data:
                      brightness: 153
                      transition: 30
                  - delay: '00:02:00'
                  - service: switch.turn_on
                    entity_id: switch.adaptive_lighting_global
                  - service: light.turn_off
                    entity_id: light.wled
                  - delay: '00:00:01'
                  - service: light.turn_off
                    entity_id: light.wled
            default:
              - service: switch.turn_on
                entity_id: switch.adaptive_lighting_global
              - delay: '00:02:00'
              - service: light.turn_off
                entity_id: light.wled
              - delay: '00:00:10'
              - service: light.turn_off
                entity_id: light.wled

media_player:
  - platform: universal
    name: Écran salon
    children:
      - media_player.yamaha_receiver
      - media_player.plex_plex_media_player_steambox
    commands:
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.projector
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.projector
      volume_up:
        service: script.turn_on
        data:
          entity_id: script.ht_volume_up
      volume_down:
        service: script.turn_on
        data:
          entity_id: script.ht_volume_down
      volume_mute:
        service: script.turn_on
        data:
          entity_id: script.ht_volume_mute
      volume_set:
        service: media_player.volume_set
        data_template:
          entity_id: media_player.yamaha_receiver
          volume_level: '{{ volume_level }}'
      select_source:
        service: media_player.select_source
        data_template:
          entity_id: media_player.yamaha_receiver
          source: '{{ source }}'
      media_play:
        service: media_player.media_play
        entity_id: media_player.plex_plex_media_player_steambox
      media_pause:
        service: media_player.media_pause
        entity_id: media_player.plex_plex_media_player_steambox
      media_stop:
        service: media_player.media_stop
        entity_id: media_player.plex_plex_media_player_steambox
      media_next_track:
        service: media_player.media_next_track
        entity_id: media_player.plex_plex_media_player_steambox
      media_previous_track:
        service: media_player.media_previous_track
        entity_id: media_player.plex_plex_media_player_steambox
    attributes:
      state: media_player.yamaha_receiver
      is_volume_muted: media_player.yamaha_receiver|is_volume_muted
      volume_level: media_player.yamaha_receiver|volume_level
      source: media_player.yamaha_receiver|source
      source_list: media_player.yamaha_receiver|source_list

automation:
  - alias: 🎬 Bring lights on during plex pause
    trigger:
      - platform: state
        entity_id: media_player.plex_plex_media_player_steambox
        to: paused
    action:
      - condition: state
        entity_id: binary_sensor.sun_up
        state: 'off'
      - service: light.turn_on
        entity_id: light.salon
        data:
          brightness: 90
          transition: 10
  - alias: 🎬 Bring lights off after plex pause
    trigger:
      - platform: state
        entity_id: media_player.plex_plex_media_player_steambox
        from: paused
    action:
      - service: light.turn_off
        entity_id: light.cuisine
      - condition: state
        entity_id: binary_sensor.sun_up
        state: 'off'
      - service: light.turn_on
        entity_id: light.salon
        data:
          brightness: 3
          transition: 10

homeassistant:
  customize:
    switch.projector:
      friendly-name: Projecteur
      icon: 'mdi:projector'
    media_player.ecran_salon:
      friendly-name: Projecteur
      device_class: tv
