# Monitors speakers using a built-in amp that uses pretty much the same amount of power
# when idle as when being used. So a Tradfri plug is used to cut main power off when idle.

automation:
  - alias: Switch monitors off if iMac is off
    trigger:
        # doesn't always work because sometimes the iMac gets insomnia and doesn't go to sleep
      - platform: state
        entity_id: binary_sensor.imac
        to: 'off'
        # Fallback
      - platform: state
        entity_id: binary_sensor.daedalus_active
        to: 'off'
        for: '01:30:00'
    action:
      - service: switch.turn_off
        entity_id: switch.light_15
  - alias: Switch monitors on if iMac is on
    trigger:
        # works but slower
      - platform: state
        entity_id: binary_sensor.imac
        to: 'on'
        # faster
      - platform: state
        entity_id: binary_sensor.daedalus_active
        to: 'on'
    action:
      - service: switch.turn_on
        entity_id: switch.light_15

homeassistant:
  customize:
    switch.light_15:
      icon: 'mdi:speaker'
      friendly_name: 'Monitors'

