# Monitors speakers using a built-in amp that uses pretty much the same amount of power
# when idle as when being used. So a Tradfri plug is used to cut main power off when idle.

automation:
  - alias: 🔈 Switch monitors off if idle
    trigger:
      - platform: state
        entity_id: sensor.daedalus_active_audio_output
        from: 'USB Audio CODEC '
        for: '00:02:00'
    action:
      - service: switch.turn_off
        entity_id: switch.ikea_plug_2

  - alias: 🔈 Switch monitors on if active
    trigger:
      - platform: state
        entity_id: sensor.daedalus_active_audio_output
        to: 'USB Audio CODEC '
    action:
      - service: switch.turn_on
        entity_id: switch.ikea_plug_2

homeassistant:
  customize:
    switch.ikea_plug_2:
      icon: 'mdi:speaker'
      friendly_name: 'Monitors'
