automation:
  - alias: Switch monitors off if iMac is off
    trigger:
      - platform: state
        entity_id: binary_sensor.imac
        from: 'on'
        to: 'off'
    action:
      - service: switch.turn_off
        entity_id: switch.light_15
  - alias: Switch monitors on if iMac is on
    trigger:
      - platform: state
        entity_id: binary_sensor.imac
        from: 'off'
        to: 'on'
    action:
      - service: switch.turn_on
        entity_id: switch.light_15

binary_sensor:
  - platform: ping
    host: 192.168.1.140
    name: iMac
    count: 2
    scan_interval: 30

homeassistant:
  customize:
    binary_sensor.imac:
      icon: 'mdi:desktop-mac'
    switch.light_15:
      icon: 'mdi:speaker'
      friendly_name: 'Monitors'
