# Mi Flora sensors interfaced using
# https://github.com/ThomDietrich/miflora-mqtt-daemon

plant:
  flowall_bureau:
    sensors:
      moisture: sensor.flowallbureau_moisture
      battery: sensor.flowallbureau_battery
      temperature: sensor.flowallbureau_temperature
      conductivity: sensor.flowallbureau_conductivity
      brightness: sensor.flowallbureau_light
    min_moisture: 20
    max_moisture: 80
    min_battery: 20
    min_conductivity: 10
    min_temperature: 15
  flowall_salon:
    sensors:
      moisture: sensor.flowallsalon_moisture
      battery: sensor.flowallsalon_battery
      temperature: sensor.flowallsalon_temperature
      conductivity: sensor.flowallsalon_conductivity
      brightness: sensor.flowallsalon_light
    min_moisture: 20
    max_moisture: 80
    min_battery: 20
    min_conductivity: 10
    min_temperature: 15

homeassistant:
  customize:
    plant.flowall_bureau:
      friendly_name: Plantes murales bureau
    plant.flowall_salon:
      friendly_name: Plantes murales salon

alert:
  bureau_plant:
    name: Les plantes murales du bureau ont besoin d'attention
    done_message: Les plantes murales du bureau vous remercient
    entity_id: plant.flowall_bureau
    state: 'problem'
    skip_first: true
    can_acknowledge: true
    repeat:
      - 20
      - 60
      - 360
    notifiers:
      - mobile_app_phophone
  salon_plant:
    name: Les plantes murales du salon ont besoin d'attention
    done_message: Les plantes murales du salon vous remercient
    entity_id: plant.flowall_salon
    state: 'problem'
    skip_first: true
    can_acknowledge: true
    repeat:
      - 20
      - 60
      - 360
    notifiers:
      - mobile_app_phophone

sensor:
  - platform: statistics
    name: lux_bureau
    entity_id: sensor.flowallbureau_light
    max_age:
      hours: 8
  - platform: statistics
    name: lux_salon
    entity_id: sensor.flowallsalon_light
    max_age:
      hours: 8

automation:
  - alias: Switch lights on during the night if plants didn't get enough light
    trigger:
      - platform: state
        entity_id: input_boolean.night_time
        from: 'off'
        to: 'on'
    condition:
      condition: or
      conditions:
        - condition: numeric_state
          entity_id: sensor.lux_bureau
          below: 250
        - condition: numeric_state
          entity_id: sensor.lux_salon
          below: 250
    action:
      - delay:
          hours: 4  # Maintain at least 4 hours of darkness
      - condition: state
        entity_id: binary_sensor.porte_chambre
        state: 'off'
      - service: switch.turn_off
        entity_id: switch.circadian_lighting_circadian_lighting
      - service: light.turn_on
        entity_id: light.bureau
        data:
          color_name: fuchsia
          brightness: 255
      - service: light.turn_on
        entity_id: light.salon
        data:
          color_name: fuchsia
          brightness: 255
