# Mi Flora sensors interfaced using
# https://github.com/ThomDietrich/miflora-mqtt-daemon

plant:
  flowall_bureau:
    sensors:
      moisture: sensor.flowallbureau_moisture
      battery: sensor.flowallbureau_battery
      temperature: sensor.flowallbureau_temperature
      conductivity: sensor.flowallbureau_conductivity
      brightness: sensor.flowallbureau_light
    min_moisture: 20
    max_moisture: 80
    min_battery: 15
    min_conductivity: 10
    min_temperature: 15
  flowall_salon:
    sensors:
      moisture: sensor.flowallsalon_moisture
      battery: sensor.flowallsalon_battery
      temperature: sensor.flowallsalon_temperature
      conductivity: sensor.flowallsalon_conductivity
      brightness: sensor.flowallsalon_light
    min_moisture: 20
    max_moisture: 80
    min_battery: 15
    min_conductivity: 10
    min_temperature: 15

homeassistant:
  customize:
    plant.flowall_bureau:
      friendly_name: Plantes murales bureau
    plant.flowall_salon:
      friendly_name: Plantes murales salon

alert:
  bureau_plant:
    name: Les plantes murales du bureau ont besoin d'attention
    done_message: Les plantes murales du bureau vous remercient
    entity_id: plant.flowall_bureau
    state: 'problem'
    skip_first: true
    can_acknowledge: true
    repeat:
      - 20
      - 60
      - 360
    notifiers:
      - mobile_app_phophone
  salon_plant:
    name: Les plantes murales du salon ont besoin d'attention
    done_message: Les plantes murales du salon vous remercient
    entity_id: plant.flowall_salon
    state: 'problem'
    skip_first: true
    can_acknowledge: true
    repeat:
      - 20
      - 60
      - 360
    notifiers:
      - mobile_app_phophone
