plant:
  flowall_bureau:
    sensors:
      moisture: sensor.plant_1_soil_moisture
      battery: sensor.plant_1_battery
      temperature: sensor.plant_1_temperature
    min_moisture: 66
    max_moisture: 95
    min_battery: 10
    min_temperature: 10
  flowall_salon:
    sensors:
      moisture: sensor.plant_2_soil_moisture
      battery: sensor.plant_2_battery
      temperature: sensor.plant_2_temperature
    min_moisture: 66
    max_moisture: 95
    min_battery: 10
    min_temperature: 10
  calathea:
    sensors:
      moisture: sensor.plant_sensor_e75d_moisture
      battery: sensor.plant_sensor_e75d_battery
      temperature: sensor.plant_sensor_e75d_temperature
      conductivity: sensor.plant_sensor_e75d_conductivity
      brightness: sensor.plant_sensor_e75d_illuminance
    min_moisture: 66
    max_moisture: 95
    min_battery: 10
    min_temperature: 10
  pothos:
    sensors:
      moisture: sensor.plant_sensor_c9da_moisture
      battery: sensor.plant_sensor_c9da_battery
      temperature: sensor.plant_sensor_c9da_temperature
      conductivity: sensor.plant_sensor_c9da_conductivity
      brightness: sensor.plant_sensor_c9da_illuminance
    min_moisture: 66
    max_moisture: 95
    min_battery: 10
    min_temperature: 10
  ficus_bureau:
    sensors:
      moisture: sensor.plant_sensor_e003_moisture
      battery: sensor.plant_sensor_e003_battery
      temperature: sensor.plant_sensor_e003_temperature
      conductivity: sensor.plant_sensor_e003_conductivity
      brightness: sensor.plant_sensor_e003_illuminance
    min_moisture: 66
    max_moisture: 95
    min_battery: 10
    min_temperature: 10

homeassistant:
  customize:
    plant.flowall_bureau:
      friendly_name: Plantes murales bureau
    plant.flowall_salon:
      friendly_name: Plantes murales salon

light:
  - platform: template
    lights:
      grow_lights:
        turn_on:
          - service: switch.turn_on
            entity_id: switch.adaptive_lighting_sleep_mode_global
          - service: light.turn_on
            entity_id:
              - light.salon
              - light.bureau
        turn_off:
          - service: switch.turn_off
            entity_id: switch.adaptive_lighting_sleep_mode_global

automation:
  - alias: 🌿 Switch grow lights on during the night
    trigger:
      - platform: state
        entity_id: binary_sensor.door_2_contact
        to: 'off'
        for: '00:05:00'
    condition:
      - condition: state
        entity_id: group.main_rooms_lights
        state: 'off'
      - condition: state
        entity_id: binary_sensor.sun_up
        state: 'off'
      - condition: state
        entity_id: group.guests
        state: 'not_home'
    action:
      - service: light.turn_on
        entity_id: light.grow_lights

  - alias: 🌿 Switch grow Lights off at sunrise or wakeup
    trigger:
      - platform: numeric_state
        entity_id: sensor.lux_1_illuminance_lux
        above: input_number.ambiant_light_dark_threshold
        for: '00:10:00'
      - platform: state
        entity_id: input_boolean.night_time
        to: 'off'
    action:
      - service: light.turn_off
        entity_id: light.grow_lights

  - alias: 🌿 Send notification when plant needs attention
    trigger:
      - platform: state
        entity_id:
          - plant.flowall_bureau
          - plant.flowall_salon
        to: problem
    action:
      - service: notify.main_devices
        data_template:
          title: "🌿 {{ state_attr(trigger.entity_id, 'friendly_name') }}"
          message: "{{ state_attr(trigger.entity_id, 'friendly_name') }} needs help ({{ state_attr(trigger.entity_id, 'problem') }})"
          data:
            tag: "plant-watering"

  - alias: 🌿 clear notification when plants have been watered
    trigger:
      - platform: state
        entity_id:
          - plant.flowall_bureau
          - plant.flowall_salon
        to: ok
    action:
      - service: notify.main_devices
        data:
          message: "clear_notification"
          data:
            tag: "plant-watering"
