media_player:
  - platform: yamaha
    host: 192.168.1.103

automation:
  - alias: 🔈 turn subwoofer on when receiver is active
    trigger:
      platform: state
      entity_id: media_player.yamaha_receiver
      from: 'off'
    action:
      - service: switch.turn_on
        entity_id: switch.ikea_plug_3
  - alias: 🔈 turn subwoofer off when receiver is inactive
    trigger:
      platform: state
      entity_id: media_player.yamaha_receiver
      to: 'off'
    action:
      - service: switch.turn_off
        entity_id: switch.ikea_plug_3
      
  - alias: 🔈 turn up volume
    trigger:
      - platform: event
        event_type: ios.action_fired
        event_data:
          actionName: Volume Up
    condition:
      condition: state
      entity_id: media_player.yamaha_receiver
      state: 'on'
    action:
      - service: script.turn_on
        entity_id: script.ht_volume_up
  - alias: 🔈 turn down volume
    trigger:
      - platform: event
        event_type: ios.action_fired
        event_data:
          actionName: Volume Down
    condition:
      condition: state
      entity_id: media_player.yamaha_receiver
      state: 'on'
    action:
      - service: script.turn_on
        entity_id: script.ht_volume_down
  - alias: 🔈 mute volume
    trigger:
      - platform: event
        event_type: ios.action_fired
        event_data:
          actionName: Volume Mute
    condition:
      condition: state
      entity_id: media_player.yamaha_receiver
      state: 'on'
    action:
      - service: script.turn_on
        entity_id: script.ht_volume_mute

  - alias: 🔈 Switch off receiver if inactive
    trigger:
      - platform: state
        entity_id: media_player.yamaha_receiver
        to: 'idle'
        for: "00:10:00"
      - platform: state
        entity_id: binary_sensor.airport_express_airplay_status
        to: 'off'
    condition:
      condition: state
      entity_id: switch.steambox
      state: 'off'
    action:
      - service: media_player.turn_off
        entity_id: media_player.yamaha_receiver

  - alias: 🔈 Switch on receiver if airplay is active
    trigger:
      platform: state
      entity_id: binary_sensor.airport_express_airplay_status
      to: 'on'
    action:
      - service: media_player.turn_on
        entity_id: media_player.yamaha_receiver
      - service: media_player.select_source
        entity_id: media_player.yamaha_receiver
        data:
          source: 'AV4'

script:
  ht_volume_up:
    alias: Volume Up
    sequence:
      - service: media_player.volume_set
        entity_id: media_player.yamaha_receiver
        data_template:
          volume_level: '{{ states.media_player.yamaha_receiver.attributes.volume_level + 0.01 }}'
  ht_volume_down:
    alias: Volume Down
    sequence:
      - service: media_player.volume_set
        entity_id: media_player.yamaha_receiver
        data_template:
          volume_level: '{{ states.media_player.yamaha_receiver.attributes.volume_level - 0.01 }}'
  ht_volume_mute:
    alias: Volume Mute
    sequence:
      - service: media_player.volume_mute
        entity_id: media_player.yamaha_receiver
        data:
          is_volume_muted: true

homeassistant:
  customize:
    media_player.yamaha_receiver:
      device_class: speaker
