media_player:
  - platform: yamaha
    host: 192.168.1.103

automation:
  - alias: turn subwoofer on when receiver is active
    trigger:
      platform: state
      entity_id: media_player.yamaha_receiver
      from: 'off'
    action:
      - service: switch.turn_on
        entity_id: switch.on_off_plug_in_unit_21
  - alias: turn subwoofer off when receiver is inactive
    trigger:
      platform: state
      entity_id: media_player.yamaha_receiver
      to: 'off'
    action:
      - service: switch.turn_off
        entity_id: switch.on_off_plug_in_unit_21
      
  - alias: turn up volume
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_wireless_dimmer
        event: 2002
    action:
      - service: script.turn_on
        entity_id: script.ht_volume_up
  - alias: turn down volume
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_wireless_dimmer
        event: 3002
    action:
      - service: script.turn_on
        entity_id: script.ht_volume_down

  - alias: Switch off receiver if inactive
    trigger:
      platform: state
      entity_id: media_player.yamaha_receiver
      to: 'idle'
      for: "00:10:00"
    condition:
      condition: state
      entity_id: switch.steambox
      state: 'off'
    action:
      - service: media_player.turn_off
        entity_id: media_player.yamaha_receiver

script:
  ht_volume_up:
    alias: Volume Up
    sequence:
      - service: media_player.volume_set
        entity_id: media_player.yamaha_receiver
        data_template:
          volume_level: '{{ states.media_player.yamaha_receiver.attributes.volume_level + 0.01 }}'
  ht_volume_down:
    alias: Volume Down
    sequence:
      - service: media_player.volume_set
        entity_id: media_player.yamaha_receiver
        data_template:
          volume_level: '{{ states.media_player.yamaha_receiver.attributes.volume_level - 0.01 }}'
  ht_volume_mute:
    alias: Volume Mute
    sequence:
      - service: media_player.volume_mute
        entity_id: media_player.yamaha_receiver
        data:
          is_volume_muted: true

homeassistant:
  customize:
    media_player.yamaha_receiver:
      device_class: speaker
