sensor:
  - platform: ring

# camera:
#   - platform: ring

ring:
  username: !secret ring_user
  password: !secret ring_password

homeassistant:
  customize:
    sensor.ring_front_door_last_activity:
      hidden: true
    sensor.ring_front_door_last_motion:
      hidden: true
    sensor.ring_front_door_last_ding:
      hidden: true
    sensor.ring_front_door_volume:
      hidden: true
    sensor.ring_front_door_wifi_signal_category:
      hidden: true
    sensor.ring_front_door_wifi_signal_strength:
      hidden: true
