binary_sensor:
  - platform: ping
    host: gw
    name: Routeur
    count: 2
    scan_interval: 30
  - platform: ping
    host: freenas
    name: Nas
    count: 2
    scan_interval: 30
  - platform: ping
    host: mirror
    name: Mirror
    count: 2
    scan_interval: 30
  - platform: ping
    host: slab
    name: Slab
    count: 2
  - platform: ping
    host: sliver
    name: Sliver
    count: 2
    scan_interval: 30
  - platform: ping
    host: slice
    name: Slice
    count: 2
    scan_interval: 30
  - platform: ping
    name: AC-AP Lite
    host: 192.168.1.62
    count: 2
    scan_interval: 30

homeassistant:
  customize:
    binary_sensor.nas:
      icon: 'mdi:nas'
    binary_sensor.mirror:
      icon: 'mdi:nas'
    binary_sensor.slab:
      icon: 'mdi:ubuntu'
    binary_sensor.sliver:
      icon: 'mdi:ubuntu'
    binary_sensor.slice:
      icon: 'mdi:ubuntu'
    binary_sensor.imac:
      icon: 'mdi:desktop-mac'
    binary_sensor.routeur:
      icon: 'mdi:router-wireless'
    binary_sensor.sync:
      icon: 'mdi:cloud-sync'
    binary_sensor.ac_ap_lite:
      icon: 'mdi:access-point-network'
