sensor:
  - platform: snmp
    host: 192.168.1.1
    community: reefab
    baseoid: 1.3.6.1.2.1.2.2.1.10.4
    name: WAN Download
    unit_of_measurement: byte
  - platform: snmp
    host: 192.168.1.1
    community: reefab
    baseoid: 1.3.6.1.2.1.2.2.1.16.4
    name: WAN Upload
    unit_of_measurement: byte
