input_boolean:
  night_time:

automation:
  - alias: 💤 Start the day when blind or door is opened
    trigger:
      - platform: state
        entity_id: cover.bedroom_blind
        from: 'closed'
        to: 'open'
      - platform: state
        entity_id: binary_sensor.porte_chambre
        to: 'on'
        for:
          minutes: 5
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.night_time

  - alias: 💤 Start the night on button press
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: bouton_lit
          event: 1004
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.night_time

  - alias: 💤 Start the night on bedroom door closing
    trigger:
      - platform: state
        entity_id: binary_sensor.porte_chambre
        to: 'off'
    condition:
      - condition: state
        entity_id: group.guests
        state: 'not_home'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.night_time
