# Gaming PC

switch:
  - platform: wake_on_lan
    name: steambox
    host: steambox.home.arpa
    mac: '0c:c4:7a:9a:2d:06'
    broadcast_address: 192.168.1.255
    turn_off:
      - service: button.press
        entity_id: button.steambox_shutdown

homeassistant:
  customize:
    switch.steambox:
      icon: 'mdi:steam'

automation:
  # for backups and stuff, will shutdown by itself after finishing
  - alias: 🎮 weekly steambox housekeeping
    trigger:
      - platform: time
        at: '08:00:00'
    condition:
      - condition: time
        weekday:
          - sun
    action:
      - service: switch.turn_on
        entity_id: switch.steambox

  - alias: 🎮 Turn steambox on via action
    trigger:
      - platform: event
        event_type: ios.action_fired
        event_data:
          actionName: Power on Steambox
    action:
      - service: switch.turn_on
        entity_id: switch.steambox
      - wait_for_trigger:
          - platform: state
            entity_id: button.steambox_1440p
            from: unavailable
      - delay: 30
      - service: button.press
        entity_id: button.steambox_1440p
