automation:
  - id: front_door_opened
    alias: front_door_has_been_opened
    trigger:
      - platform: state
        entity_id: binary_sensor.porte_entree
        from: 'off'
        to: 'on'
    action:
      - service: notify.mobile_app_phophone
        data:
          message: "request_location_update"

map:
