# Monitoring a UPS connected via USB to a freenas server using https://networkupstools.org
homeassistant:
  customize:
    sensor.nut_ups_battery_runtime:
      friendly_name: UPS runtime
    sensor.nut_ups_load:
      friendly_name: UPS load
