switch:
  - platform: mqtt
    name: Main Water Valve
    state_topic: "stat/water_valve/POWER"
    command_topic: "cmnd/water_valve/POWER"
    availability_topic: "tele/water_valve/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    payload_on: "OFF"
    payload_off: "ON"
    retain: true

automation:
  - alias: Shut water valve in case of leaks
    # To prevent false positives during startup if the sensors are not ready yet
    initial_state: false
    trigger:
      - platform: state
        from: 'off'
        to: 'on'
        entity_id: binary_sensor.water_12
      - platform: state
        from: 'off'
        to: 'on'
        entity_id: binary_sensor.compteur_eau
      - platform: state
        from: 'off'
        to: 'on'
        entity_id: binary_sensor.buanderie
    action:
      service: switch.turn_off
      entity_id: switch.main_water_valve
  - alias: Activate leak prevention automation
    trigger:
      platform: homeassistant
      event: start
    action:
      - delay:
          seconds: 120
      - service: automation.turn_on
        entity_id: automation.shut_water_valve_in_case_of_leaks

homeassistant:
  customize:
    switch.main_water_valve:
      icon: 'mdi:pipe'
    automation.activate_leak_prevention_automation:
      hidden: true
