switch:
  # Custom device with a motorized ball valve and a modified zigbee switch to
  # create a connected main water valve. Documentation available here:
  # https://github.com/reefab/homeassistant-water-valve
  - platform: template
    switches:
      water_valve:
        value_template: "{{ is_state('light.valve', 'off') }}"
        turn_on:
          service: light.turn_off
          entity_id: light.valve
        turn_off:
          service: light.turn_on
          entity_id: light.valve

automation:
  - alias: Shut water valve in case of leaks
    trigger:
      - platform: state
        to: 'on'
        entity_id: 
          - binary_sensor.robinet_toilette
          - binary_sensor.compteur_eau
          - binary_sensor.buanderie
    action:
      service: switch.turn_off
      entity_id: switch.water_valve

homeassistant:
  customize:
    switch.water_valve:
      icon: 'mdi:pipe'
