switch:
  # Custom device with a motorized ball valve and a modified zigbee switch to
  # create a connected main water valve. Documentation available here:
  # https://github.com/reefab/homeassistant-water-valve
  - platform: template
    switches:
      water_valve:
        value_template: "{{ is_state('switch.valve', 'off') }}"
        turn_on:
          service: switch.turn_off
          entity_id: switch.valve
        turn_off:
          service: switch.turn_on
          entity_id: switch.valve

automation:
  - alias: Shut water valve in case of leaks
    trigger:
      - platform: state
        to: 'on'
        entity_id:
          - binary_sensor.leak_1
          - binary_sensor.leak_2
          - binary_sensor.leak_3
    action:
      service: switch.turn_off
      entity_id: switch.water_valve

homeassistant:
  customize:
    switch.water_valve:
      icon: 'mdi:pipe'
