weather:
  - platform: darksky
    api_key: !secret dark_sky_api

sensor:
  - platform: darksky
    api_key: !secret dark_sky_api
    forecast:
      - 0
    monitored_conditions:
      - temperature
      - apparent_temperature
      - apparent_temperature_high
    scan_interval:
      hours: 1
